import { Artwork } from "./types";

export const ARTWORKS: Artwork[] = [
  {
    id: "inf-alhamdulillah",
    titleAr: "رمز اللانهاية والتسبيح",
    titleEn: "The Infinity Cycle - Alhamdulillah",
    subtitleAr: "عمل يدوي أصيل ملوّن بالذهبي الفاخر",
    subtitleEn: "Original Hand-Painted Artwork in Premium Frame",
    price: 200,
    image: "/images/real_infinity_alhamdulillah.jpeg",
    category: "luxury",
    size: "42x32 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «رمز اللانهاية والتسبيح» تجمع بين حلقة اللانهاية (∞) المرسومة يدوياً وكتلة كوفية تربيعية تقرأ «الحمد لله رب العالمين»، حيث يتحوّل التسبيح إلى حركة بصرية لا تنتهي، ويُحسب سمك الحلقة ليطابق تماماً سمك حروف الكتلة الأفقية أدناها.",
    descriptionEn: "A hand-painted gold infinity loop (∞) floats above a Square Kufic block reading 'Alhamdulillah Rabb Al-Alamin' on deep black. The loop stroke width matches the letter thickness exactly, creating a single unified visual object.",
    essayTitleAr: "حلقة اللانهاية فوق كتلة 'الحمد لله': حين يصبح رمز ∞ خطاً كوفياً مقدساً",
    essayTitleEn: "The Infinity Loop Above 'Alhamdulillah': When the ∞ Symbol Becomes Sacred Square Kufic",
    spiritualAr: "تعبر هذه اللوحة المبتكرة عن تدفق الحمد والتسبيح كقوة حيوية مستمرة لا تحدها حدود ولا أبعاد. مستوحاة من روعة الإيمان اللامتناهي وعلاقة المخلوق بالخالق التي تتجاوز الزمن والمكان، تلتف حركات الحرف الكوفي لتصنع تمثيلاً روحانياً مهيباً يربط الأرض بالسماء ويذكر المتأمل في دوام نعم الله وحمده المتواصل.",
    spiritualEn: "This ground-breaking composition manifests praise (Alhamdulillah) as a continuous, unbounded cosmic force. Drawing inspiration from infinite faith and the eternal relationship with the Creator, the letters curve dynamically to map out a spiritual cycle that visually floats between space and time, prompting the viewer to reflect on the endless flow of grace.",
    geometricAr: "تعتمد اللوحة على هندسة كوفية تربيعية صارمة بنسبة تماثل كاملة 1:1. تتناغم الانحناءات اللانهائية المرسومة يدوياً ببريق اللون الذهبي الفاخر مع قاعدة معمارية أفقية صلبة مكتوب بها 'الحمد لله رب العالمين'، مما يحقق توازناً فيزيائياً وجمالياً معقداً يبهر الأبصار ويثبت وقاراً في المساحة المعروضة بها.",
    geometricEn: "Built upon a strict 1:1 grid, the mathematical rhythm matches the character thickness with negative space. The golden custom-painted infinity path loops elegantly above a block base spelling 'Alhamdulillah', achieving an intricate equilibrium between flowing curvature and bold architectural calligraphy."
  },
  {
    id: "bismillah-horizontal",
    titleAr: "الميزان الهندسي - البسملة المباركة",
    titleEn: "Perfect Proportion - Bismillah Scroll",
    subtitleAr: "تكوين أفقي يدوّي فاخر",
    subtitleEn: "Original Canvas in Premium Gallery Frame",
    price: 200,
    image: "/images/real_bismillah_horizontal.jpeg",
    category: "luxury",
    size: "56x30 سم",
    limitedEdition: true,
    descriptionAr: "تحفة «الميزان الهندسي — البسملة المباركة» تعرض «بسم الله الرحمن الرحيم» بالخط الكوفي المربع عبر لوحة أفقية عريضة، حيث يتناسق توزيع الحروف في ميزان هندسي دقيق يعكس توازن الرحمة والجلال، مرسومة يدوياً ومحاطة بإطار معرض فاخر.",
    descriptionEn: "'Bismillah Ar-Rahman Ar-Rahim' written in Square Kufic across a wide horizontal canvas in brilliant gold on deep black, enclosed in a premium gallery frame with anti-glare museum glass protection.",
    essayTitleAr: "البسملة الشريفة أفقياً: تشريح التوازن الرياضي لحروف الرحمة على اللوحة العريضة",
    essayTitleEn: "Bismillah Across the Horizontal Canvas: Anatomy of Gold Square Kufic Symmetry",
    spiritualAr: "البسملة هي بَدء النور ومفتاح كل فلاح روحي ومادي. صاغها الفنان محسن نصائيبة هنا كبوابة بصرية وافرة السكينة تدعو المتأمل للوقوف عند جلال الكلمات واستحضار البركة والرحمة وسكينة النفوس الطامحة للتكامل والهدوء الداخلي.",
    spiritualEn: "The Bismillah is the genesis of divine light and the lock-key to all spiritual prosperity. The artist captures its essence here as a serene visual gate, inviting observers to pause, contemplate the weight of sacred script, and invoke absolute peace and composure.",
    geometricAr: "تكاملت عناصر الهندسة البصرية في هذه التحفة الأفقية الممتدة عبر ميزان متناظر دقيق للغاية. تم توزيع الحروف لتلتئم الفراغات البينية بدقة متناهية، وبطريقة تجعل المساحات السلبية (الخلفية العميقة) تتحدث بنفس الفخامة الموازية لخطوط الحروف الذهبية البراقة والدافئة.",
    geometricEn: "This horizontal scroll highlights perfect horizontal distribution. The lettering layout is engineered dynamically, ensuring that the negative spaces (deep background blocks) carry the same aesthetic narrative as the hand-painted gold-acrylic letterforms."
  },
  {
    id: "wa-jaalna-muttaqin",
    titleAr: "محراب الصالحين - لا إله الله محمد رسول الله ا",
    titleEn: "The Sovereign Witness - Rasul Allah",
    subtitleAr: "بناء كوفي عمودي أصيل",
    subtitleEn: "Vertical Masterpiece in Wooden Frame",
    price: 280,
    image: "/images/real_wa_jaalna_muttaqin.jpeg",
    category: "geometric",
    size: "52x38 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «محراب الصالحين — لا إله إلا الله محمد رسول الله» ترتفع بشهادة التوحيد في تكوين عمودي شاهق، حيث تتشابك الشهادة في شبكة كوفية تربيعية متشابكة، ويصعد الحرف الكوفي كأعمدة محرابية تحاكي هيكلية المآذن والمحاريب.",
    descriptionEn: "A tall vertical Square Kufic grid of 'La ilaha illa Allah Muhammad Rasul Allah' hand-painted in warm gold with bright yellow accent strokes on deep black. The letters interlock and rise to mimic the vertical structure of historic mosque minarets.",
    essayTitleAr: "الشهادتان عمودياً: كيف ترتفع 'لا إله إلا الله محمد رسول الله' في شبكة كوفية متشابكة",
    essayTitleEn: "The Twin Testimonies Rising Vertically: Interlocking Square Kufic in Warm Gold and Yellow",
    spiritualAr: "تجسد اللوحة جوهر شهادة التوحيد 'لا إله إلا الله محمد رسول الله' التي تعد ركيزة اليقين وأصل السعادة. تشرق تفاصيل اللوحة بلمسات دافئة من الأصفر الباهي واللمعان الفاخر لتنبض بطاقة نورانية تجعل من الفراغ محراباً للذكر الصافي والتأسي الروحي الدائم.",
    spiritualEn: "This vertical masterpiece structures the foundation of faith: the twin testimonies. Radiating with warm yellow highlights, it acts as a geometric sanctuary for peaceful contemplation, providing continuous spiritual protection and connection to the divine.",
    geometricAr: "بنيت اللوحة على هيكلية صاعدة عالية الارتفاع مستوحاة من عمارة المحاريب والمآذن التاريخية الكبرى. تتشابك صاعدات وحركات الحروف وتتداخل بنسب رياضية فريدة، تظهر مهارة فنية يدوية خارقة للعادة في موازنة الكتل الكثيفة والتقاطعات المعقدة للخط الكوفي التربيعي.",
    geometricEn: "Taking cues from classical Islamic arches and minarets, this vertical layout features a complex grid lock. The interlocking nature of long vertical letters exhibits extreme hand craftsmanship, neutralizing visual weight and establishing a grand vertical presence."
  },
  {
    id: "fatiha-star",
    titleAr: "سورة الفاتحة المباركة",
    titleEn: "The Sacred Surah Al-Fatiha",
    subtitleAr: "الهيكل المعماري والتقسيم الهندسي",
    subtitleEn: "The Stepped Architectural Masterpiece",
    price: 450,
    image: "/images/real_colorful_stripes.jpeg",
    category: "geometric",
    size: "76x55 سم",
    limitedEdition: true,
    descriptionAr: "«سورة الفاتحة المباركة» تُجسَّد هنا في سبعة صفوف أفقية متدرجة من الخط الكوفي المربع، يقابل كل صف آية من آيات السورة السبع، ويفصل بين الصفوف شريط أفقي يمنح اللوحة بنية معمارية متدرجة، مرسومة يدوياً بالكامل على لوح خشبي.",
    descriptionEn: "All seven verses of Surah Al-Fatiha arranged in seven stepped horizontal rows of Square Kufic, each row separated by a horizontal orange divider line, painted in warm gold on a deep matte black wood panel.",
    essayTitleAr: "سبعة صفوف لسبع آيات: التصميم المعماري المتدرج لسورة الفاتحة بالخط الكوفي الذهبي",
    essayTitleEn: "Seven Verses, Seven Rows: The Stepped Architectural Layout of Surah Al-Fatiha with Orange Dividers",
    spiritualAr: "سورة الفاتحة هي أعظم سور القرآن الشريف والسبع المثاني التي تجمع معاني الهدى والحمد والدعاء بالهداية. صممت هذه التحفة الفنية المهيبة لتكون صرحاً جمالياً يملأ البيت بركة وسكينة ويدعو للتأمل العميق في إيقاع الحروف الكريمة ومعانيها الإلهية الخالدة.",
    spiritualEn: "Surah Al-Fatiha is the central pillar of the Holy Quran. Structured as a grand typographic monument, this painting fills its surrounding space with deep blessing, tranquility, and visual awe, guiding the soul through the rhythmic flow of the sacred verses.",
    geometricAr: "تعد هذه اللوحة درة المعروضات وصرحاً معمارياً مرسوماً يدوياً بالكامل. ترتصف آيات السورة الكريمة في سبع سطور أفقية كحجارة الأبنية الإسلامية العريقة، يفصل بينها شريط أفقي برتقالي يمنح البناء بعداً حركياً متدرجاً. وتكتسي الحروف بلمعان ذهبي مغمور بالدفء لإظهار تباين رائع ووقار ملكي على الأرضية السوداء الفاخرة.",
    geometricEn: "The absolute crown jewel of the collection. The entire Surah is presented across seven parallel stepped rows, reminiscent of historic stone masonry. A vibrant orange boundary line runs horizontally, giving dynamic movement while deep gold leaf accents float with royal dignity against the velvet black background."
  },
  {
    id: "calligraphic-mosque",
    titleAr: "أية قرآنية بالكتابة التربيعية",
    titleEn: "Sacred Quranic Verse in Square Kufic",
    subtitleAr: "عمارة الحروف الكوفية",
    subtitleEn: "Architectural Kufic in Luxury Frame",
    price: 400,
    image: "/images/real_calligraphic_architecture.jpeg",
    category: "lettering",
    size: "66x56 سم",
    limitedEdition: true,
    descriptionAr: "في لوحة «آية قرآنية بالكتابة التربيعية»، تُكتب الآية الكريمة بالخط الكوفي المربع بتقنية تراكب خشبي ثلاثي الأبعاد، فتتحول الحروف إلى صرح معماري نابض بالحياة يمنح العمل عمقاً نحتياً بارزاً.",
    descriptionEn: "A Quranic verse executed in three-dimensional wooden overlay Square Kufic, finished in a warm chromatic gradient flowing from dark crimson through orange and gold to sky-blue accents, giving the letters a sculptural, raised-relief depth.",
    essayTitleAr: "التراكب الخشبي والتدرج اللوني الرباعي: حروف كوفية نحتية بين الأحمر والذهبي والأزرق",
    essayTitleEn: "Wood Relief and Four-Color Gradient: Square Kufic Letters as Sculpted Architecture",
    spiritualAr: "لوحة فنية تنبض بالحيوية والعمق، تجمع ببراعة بين فخامة الآية الكريمة ودفء الانتماء والتراث. تتكامل الحروف الكوفية التربيعية لتبدو مثل صروح نورية وحصون روحية تحرس مساحتكم الخاصة وتبث الأمل والتجدد بفضل طيفها اللوني المشرق.",
    spiritualEn: "Spiritual writing with vibrant contemporary aesthetics. The sacred calligraphy aligns into a colorful visual shield, guarding your space with divine peace. The carefully computed warm gradient represents hope, spiritual renewal, and the infinite beauty of Quranic revelations.",
    geometricAr: "عمل فني كوفي رائد يتميز بتراكبات خشبية ثلاثية الأبعاد مرسومة بلمسات متدرجة تتراوح بين الأحمر القاني والبرتقالي والذهبي، مع مساحات زرقاء سماوية تمنح اللوحة عمقاً بصرياً نادراً. جرى تقييم زوايا التقاطع بمقاييس هندسية مشددة تجمع بين أصالة الخط المعاصر وحيوية الفنون التشكيلية الحديثة لتدوم اللوحة لقرون.",
    geometricEn: "An avant-garde Square Kufic composition employing wood overlays painted with a rich warm chromatic gradient. Beautiful accents of deep crimson, fiery orange, and sky blue create exceptional relief depths, fusing age-old calligraphic rules with abstract modern sculpture."
  },
  {
    id: "shahada-interlocking",
    titleAr: "سورة الإخلاص",
    titleEn: "The Testimony ",
    subtitleAr: "سورة الإخلاص بخط كوفي تربيعى",
    subtitleEn: "Geometric interlocking of the Testimony in gold & orange",
    price: 280,
    image: "/images/article_7_1897484418.jpeg",
    category: "geometric",
    size: "50x40 سم",
    limitedEdition: true,
    descriptionAr: "«سورة الإخلاص» كاملة — من «قل هو الله أحد» إلى ختامها — منسوجة في صفوف كوفية أفقية كثيفة ومتداخلة بالخط الكوفي المربع، لتجسد عقيدة التوحيد الخالص في نسيج هندسي مغناطيسي البصر.",
    descriptionEn: "Surah Al-Ikhlas ('Qul huwa Allahu Ahad...') woven into dense interlocking parallel rows of Square Kufic, accented with warm orange highlights and gold on deep black. The tight horizontal braiding creates a powerful, visually magnetic presence.",
    essayTitleAr: "سورة الإخلاص في صفوف كوفية متداخلة: الآيات الأربع منسوجة في نسيج هندسي برتقالي وذهبي",
    essayTitleEn: "Surah Al-Ikhlas in Interlocking Kufic Rows: Four Verses Woven into a Dense Orange-and-Gold Tapestry",
    spiritualAr: "تنهض شهادة التوحيد في القلب لتضيء بنورها النفوس وتطهر الضمائر. هذا التكوين الشريف بألوانه النارية الذهبية يعبر عن قوة الإيمان ورسوخه الشبيه بالبنيان المرصوص، حيث تلتف الكلمات وتتداخل مثل خيوط الشمس الذهبية لتغمر الفضاء المنزلي بفيض من السكينة والطاقة الإيجابية المباركة.",
    spiritualEn: "The holy shahada rises in the human heart to purify intentions and ignite divine awareness. Painted with rich fire-orange and brilliant gold lacquers, this vertical tapestry channels the indomitable strength of absolute belief, casting warm spiritual protection and infinite tranquil energy.",
    geometricAr: "تتميز اللوحة بتوزيع أفقي متوازن ومعشق بدقة متناهية عبر شبكة كوفية تربيعية صارمة. المحاذاة المتوازية للحروف تبرز العلاقة الجمالية بين الكتلة والفراغ، حيث يذوب الحبر الفاخر والذهبي في تباينات كوفية تفرض وقاراً هندسياً فريداً لخطوط التوحيد الممدودة بدقة سطرًا بسطر.",
    geometricEn: "This masterpiece demonstrates complex horizontal interlocking over a precise grid where letter strokes and negative spacing are perfectly calculated. Warm gradients of metallic gold and deep sunset orange intersect to resolve high-frequency visual tensions, offering majestic structural depth."
  },
  {
    id: "surah-ikhlas-grid",
    titleAr: "وَإِذْ جَعَلْنَا الْبَيْتَ مَثَابَةً لِّلنَّاسِ وَأَمْنًا ",
    titleEn: "Surah Al-Ikhlas - Absolute Monotheism",
    subtitleAr: "تكوين مستطيل دقيق وراقي بالخط الكوفي التربيعي مأخوذ من سورة البقرة الآية 125",
    subtitleEn: "Elegant rectangular grid of Surah Al-Ikhlas",
    price: 300,
    image: "/images/article_8_1182037366.jpeg",
    category: "geometric",
    size: "53x37 سم",
    limitedEdition: true,
    descriptionAr: "آية «وَإِذْ جَعَلْنَا الْبَيْتَ مَثَابَةً لِّلنَّاسِ وَأَمْنًا» من سورة البقرة مرتبة في شبكة كوفية مستطيلة دقيقة صفاً بصف، يعلوها صف البسملة الشريفة بارزاً في أعلى التكوين، في بناء يربط بين الأمن والمثابة والقداسة المعمارية للبيت.",
    descriptionEn: "Surah Al-Ikhlas arranged in a tight rectangular Square Kufic grid of sequential rows, with the opening Bismillah row highlighted in a bold yellow-ochre band at the top, and the four verses below in hand-painted gold on deep black.",
    essayTitleAr: "شبكة الإخلاص المستطيلة: صف بسملة أصفر وأربع آيات ذهبية في كتلة كوفية محكمة",
    essayTitleEn: "Surah Al-Ikhlas in a Rectangular Grid: Yellow Bismillah Header and Four Golden Verses Below",
    spiritualAr: "تعد سورة الإخلاص ثلث القرآن الكريم، وتجسد عقيدة التوحيد الخالص ونقاء التوجه لله الأحد الصمد. صِيغت السورة الكريمة هنا لتملأ الروح بجلال الاستغناء والتوكل المطلق، حيث يشع اللون الأصفر الياقوتي البهي ناصعاً ليدخل شعاعاً من الأمان والبركات والأنوار الإلهية إلى الفراغ المعماري للفراغات الراقية.",
    spiritualEn: "Representing one-third of the Quran, Surah Al-Ikhlas houses the core dogma of pure monotheism. Rendered with beautiful ochre-gold tones, this painting functions as a spiritual hearth of divine protection, invoking deep meditation on the absolute independence and eternal nature of the Creator.",
    geometricAr: "ترتصف آيات السورة الأربعة داخل قالب مستطيل فائق الدقة، حيك يدوياً خطاً بخط بدقة هندسية شاملة. تتناظر الفراغات بين الحروف لتصنع شبكة متكاملة البنية الكوفية المربعة، يعتليها خط ذهبي باهٍ يبين مطلع البسملة الشريفة ويفصل حروفها بنقاء ووقار ملكي باهر.",
    geometricEn: "The entire Surah is meticulously integrated inside an ultra-precise rectangular block. The character thickness dynamically shares identical proportions with the background voids, while Bismillah stands out at the top on a bright yellow-ochre highlighting row, maintaining pure structural rigor."
  },
  {
    id: "qurrat-ayun-imama",
    titleAr: "لا إله إلا الله محمد رسول الله ",
    titleEn: "Comfort of the Eyes - Wa'je'alna",
    subtitleAr: "بناء معماري باللونين الذهبي والأصفر الباهي و الأزرق ",
    subtitleEn: "Architectural Kufic in gold with yellow accents",
    price: 280,
    image: "/images/article_9_156253947.jpeg",
    category: "geometric",
    size: "52x37 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «لا إله إلا الله محمد رسول الله» تُبنى كبوابة كوفية طولية شاهقة، حيث ترتفع الشهادة في عمودين يتوجهما قوس معشق بدقة بالغة، في مشهد يجسد عظمة التوحيد ورسالة النبوة كصرح معماري كوفي مقدس.",
    descriptionEn: "'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama' structured as a tall golden portal: twin vertical Kufic columns topped by an intricate braided arch crown, with warm saffron-yellow accent highlights on black.",
    essayTitleAr: "دعاء الصالحين كبوابة كوفية: 'واجعلنا للمتقين إماما' في عمودين ذهبيين وتاج قوسي معشق",
    essayTitleEn: "The Family Prayer as a Kufic Portal: 'Waj'alna Lil-Muttaqina Imama' in Twin Gold Columns and Braided Arch",
    spiritualAr: "تعبر الآية الكريمة 'واجعلنا للمتقين إماما' عن سعي العائلة والمسلم لبلوغ أرفع مراتب الصلاح والقدوة الطيبة التي تقر بها الأعين وتطيب بها القلوب. صممت هذه البوابة لتكون مناراً للرحمة، تنشر الدفء وتذكر الساكنين بأهمية العطف والصبر ولم شمل الأسرة والارتقاء الروحي الدائم.",
    spiritualEn: "The holy prayer 'And make us leaders of the righteous' charts the aspiration of the family unit to achieve supreme heights of virtue. Hand-fashioned in warm gold leaf, this calligraphic sanctuary infuses any environment with feelings of mutual respect, domestic blessing, and moral uprightness.",
    geometricAr: "بنيت اللوحة على شكل محراب مئذني شاهق ترتفع دعامتاه الكوفيتان يدوياً، ويعلوه تجسيد معشق ومضفر بدقة بالغة التعقيد. يبرز التصميم توازناً فريداً في استخدام درجات الذهب والأصفر الباهي لإخراج تفاصيل الظلال وحفر الفراغات البينية بدقة متناهية ودون أي تداخل عشوائي.",
    geometricEn: "Engineered as an architectural archway, the layout features twin vertical columns supporting a highly intricate braided crown. The deliberate palette blending brilliant gold leaf with warm saffron-yellow accents provides exceptional relief contrast, separating each structural line effortlessly."
  },
  {
    id: "spectral-gradient",
    titleAr: "وَمَا يَنْطِقُ عَنِ الْهَوَى * إِنْ هُوَ إِلَّا وَحْيٌ يُوحَى",
    titleEn: "The Spectral Calligraphy",
    subtitleAr: " سورة النجم (الآيتان 3-4)",
    subtitleEn: "Warm gradient stripes with central blue testimony square",
    price: 170,
    image: "/images/article_10_1018838701.jpeg",
    category: "lettering",
    size: "51x32 سم",
    limitedEdition: true,
    descriptionAr: "آيتا سورة النجم «وَمَا يَنْطِقُ عَنِ الْهَوَى * إِنْ هُوَ إِلَّا وَحْيٌ يُوحَى» مكتوبتان بالخط الكوفي المربع داخل مربع مائل بزاوية 45 درجة في المركز، يحيط بهما شرائط رأسية متوازية، في تكوين يربط بين الوحي الإلهي والتقارب البصري نحو محور الحق.",
    descriptionEn: "The twin testimonies placed inside a central 45-degree tilted royal blue diamond, flanked by vertical color bands flowing from golden yellow through deep crimson to orange, creating a visual sense of warmth converging inward to the sacred core.",
    essayTitleAr: "الماسة الزرقاء والشرائط الحارة: الشهادتان في مركز طيف لوني يتقارب نحو الداخل",
    essayTitleEn: "The Blue Diamond and the Warm Stripes: Twin Testimonies at the Center of a Spectral Color Convergence",
    spiritualAr: "تلتقي ألوان الطيف النارية لتعبّر عن فيض الطاقة والحياة في الكون، بينما يتوسط التكوين مربع الشهادتين الأزرق كمركز ثابت للحق واليقين. تبعث اللوحة طاقة إيمانية دافئة، وتدعو المتأمل لاستكشاف النور الكامن في جوهر شهادة الحق التي تدور حولها الأفلاك والخلائق بسلام وأمان.",
    spiritualEn: "Dynamic spectrums of primary warmth meet inside this calligraphic canvas, framing a central 45-degree blue diamond that carries the twin testimonies of faith. It visually represents the cosmic universe swirling in praise around the absolute axis of divine truth, radiating joy, hope, and visual comfort.",
    geometricAr: "توازن هندسي رفيع يجمع بين خطوط رأسية متوازية بدقة متناهية تحمل الألوان النارية المتدرجة، ومربع مركزي مائل بزاوية 45 درجة مرسوم باللون الأزرق الملكي النقي. التقاطع بين الزوايا المائلة والأسطر الرأسية يظهر حنكة عريقة ليد الفنان في موازنة الكتل الكبيرة.",
    geometricEn: "This masterpiece orchestrates vertical stripe arrays in hot gradients (yellow, crimson, orange) intersecting a prominent 45-degree diamond cartouche in rich navy blue. The visual friction between the vertical parallel tracks and the inclined central block captures the mathematical essence of contemporary Kufic abstraction."
  },
  {
    id: "mihrab-al-khairat",
    titleAr: "سبحان الله * الحمد لله * الله أكبر ",
    titleEn: "The Pavilion of Charity - Wa Ma Tuqaddimu",
    subtitleAr: "التسبيح و الحمد و التكبير بالخط التربيعي",
    subtitleEn: "Bespoke archway calligraphy in orange and gold lacquer",
    price: 130,
    image: "/images/article_11_1399066410.jpeg",
    category: "luxury",
    size: "52x26 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «سبحان الله * الحمد لله * الله أكبر» تجمع التسبيح والحمد والتكبير في شبكة كوفية تربيعية تحت قوس دائري محرابي، في مشهد يحوّل الأذكار الثلاثة إلى محراب بصري للذكر والشكر.",
    descriptionEn: "'Wa ma tuqaddimu li-anfusikum min khayr tajidohu indallah' written in Square Kufic beneath a bold semicircular ochre-orange arch, with warm gold and orange letter colors on a deep black background.",
    essayTitleAr: "تحت القوس الأوكري: 'وما تقدموا لأنفسكم من خير' وهندسة القوس المحرابي المتناظر",
    essayTitleEn: "Under the Ochre Arch: 'Wa Ma Tuqaddimu Li-Anfusikum' and the Geometry of Generosity",
    spiritualAr: "تذكرنا الآية الكريمة 'وما تقدموا لأنفسكم من خير تجدوه عند الله' بأن الإحسان والصدقة هما الذخر الحقيقي الذي يبقى للروح ويطهرها من درن البخل. صممت اللوحة تحت قبة محرابية صفراء لتفيض بالبركات والرحمة الإلهية الوافرة، مستحضرةً طاقة الجود لتزين أركان مساحتكم المعيشية بالسكينة.",
    spiritualEn: "The sacred verse 'And whatever good you send forth for your souls, you will find it with Allah' serves as a guiding light for timeless generosity. Nested under a golden spiritual alcove, this calligraphy introduces themes of cosmic balance, altruism, and peaceful charity into private living rooms.",
    geometricAr: "تكوين محرابي كلاسيكي مبني يدوياً وفق نسب هندسية رصينة ومحسوبة بدقة. ترتصف الكلمات تحت قوس دائري مذهب متطابق الأبعاد بلون برتقالي وذهبي كلاسيكي مبهج، مما يبرز تباين الألوان وعمق الشبكة التربيعية الكوفية التي توازن الكتل والفرغات بنفس الوقار والاتزان.",
    geometricEn: "Highly classical archway proportions govern this composition. The sacred script registers perfectly within a bold semicircular gold-and-orange dome, highlighting the artist's ability to maintain grid continuity across both circular curves and block-based calligraphic foundations."
  },
  {
    id: "turquoise-pillar",
    titleAr: "خُذْ مِنْ أَمْوَالِهِمْ صَدَقَةً تُطَهِّرُهُمْ وَتُزَكِّيهِمْ بِهَ",
    titleEn: "The Golden Pillar on Royal Blue",
    subtitleAr: "سُورَةِ التَّوْبَة (الآية 103",
    subtitleEn: "Vertical golden column on deep royal blue background",
    price: 160,
    image: "/images/article_12_563872318.jpeg",
    category: "luxury",
    size: "51x39 سم",
    limitedEdition: true,
    descriptionAr: "آية «خُذْ مِنْ أَمْوَالِهِمْ صَدَقَةً تُطَهِّرُهُمْ وَتُزَكِّيهِمْ بِهَا» من سورة التوبة مكتوبة بالخط الكوفي المربع في عمود رأسي طويل واحد، في تكوين يربط بين الزكاة والتطهير والصفاء البصري.",
    descriptionEn: "'Alhamdulillah Rabb Al-Alamin' arranged as a single tall vertical Square Kufic column, fully hand-painted in brilliant gold, mounted on a deep royal indigo-blue velvet background.",
    essayTitleAr: "عمود الحمد الذهبي الواحد: 'الحمد لله رب العالمين' رأسياً على مخمل الإنديغو الملكي",
    essayTitleEn: "The Single Gold Vertical Pillar: 'Alhamdulillah Rabb Al-Alamin' Rising on Deep Indigo Velvet",
    spiritualAr: "الحمد هو منبع كل زيادة ونعمة وراحة للبال. صِيغت عبارة 'الحمد لله رب العالمين' بلمسة كوفية طولية مذهبة تنساب كمنار النور وصرح الشكر على أرضية فيروزية كحلية تشع صفاء وهدوءاً، لتملأ مساحتكم الخاصة بروح الامتنان والسلام الدائم.",
    spiritualEn: "Expression of praise (Alhamdulillah) is the bedrock of cosmic abundance and tranquil satisfaction. Carved as a singular vertical gilded pillar on an deep indigo-turquoise canvas, this artwork acts as a beacon of mindfulness, radiating continuous gratitude and divine balance.",
    geometricAr: "تعتمد اللوحة الهيكل الطولي الرأسي الشاهق ذو المحاذاة المشددة بدقة بالغة. تم تذهيب الحروف الكوفية التربيعية يدوياً بالكامل، وتركيبها بأعماق بصرية مدروسة على سجادة فيروزية ملكية لتظهر التباين المذهل والتفافات الحواف القائمة بنسبة تماثل هندسي مثالية لجمال الفن الاستقرائي.",
    geometricEn: "Adopting a highly structured vertical monolithic pillar, the characters flow strictly along a vertical axis. Hand-painted in rich gold leaf, the raised letterforms are mounted on deep indigo-turquoise velvet, emphasizing the beautiful straight Kufic corners and perfect proportions of blank versus gold blocks."
  },
  {
    id: "gate-of-forgiveness",
    titleAr: "الملك لله ",
    titleEn: "Hasten to Forgiveness - Wa Sarei'oo",
    subtitleAr: "لوحة أفقية كوفية تربيعية ",
    subtitleEn: "Horizontal architectural plaque featuring 'Wa Sarei'oo'",
    price: 200,
    image: "/images/article_13_627657041.jpeg",
    category: "geometric",
    size: "51x31 سم",
    limitedEdition: true,
    descriptionAr: "عبارة «الملك لله» مصاغة في شبكة كوفية أفقية مزدوجة الطبقات محاطة بإطار مستطيل بارز، في لوحة أفقية تؤكد أن الملك والملكوت لله وحده، وتمنح الفراغ وقاراً ملكياً كوفياً.",
    descriptionEn: "'Wa sari'oo ila maghfirating min rabbikum wa jannatin ardhuha as-samawatu wal-ard' set in a double-layer horizontal Square Kufic grid, neatly framed within a bold orange rectangular border on black background.",
    essayTitleAr: "شبكة كوفية مزدوجة الطبقات بإطار برتقالي: 'وسارعوا إلى مغفرة من ربكم' كحصن أفقي",
    essayTitleEn: "Double-Layer Kufic Within Orange Borders: 'Wa Sari'oo' as a Horizontal Gate of Forgiveness",
    spiritualAr: "تحمل الآية الكريمة 'وسارعوا إلى مغفرة من ربكم وجنة...' نداء الأمل والتوبة المفتوح لجميع الخلائق. صُممت اللوحة كبوابة أفقية ذهبية تدعو القلوب للمبادرة لنيل الرضوان والمحبة الإلهية الوافرة، مما يضفي أجواء مفعمة بالأمل والتسامح والسلام الداخلي والبركات الطيبة.",
    spiritualEn: "The Quranic call 'Hasten to forgiveness from your Lord and a garden...' instills boundless hope and spiritual redemption in the soul. Cast as a massive horizontal golden portal, it invites observers to let go of regret and step into spiritual elevation, wrapping any space with sublime serenity.",
    geometricAr: "اللوحة مصاغة في فلك شبكة كوفية تربيعية ثنائية الطبقات تتسم بالمتانة والرسوخ المعماري. الحواف الكوفية مطوقة ومحددة بشريط أفقي برتقالي ياقوتي متميز اللون، مما يعطي توازناً استاتيكياً فريداً لخطوط الآية ويمنح الفراغات البينية طابعاً منظماً وراقياً كوفياً.",
    geometricEn: "This horizontal masterpiece utilizes a double-layered rectangular grid system of block calligraphy. The entire script is neatly bound within a vibrant rust-orange frame, neutralizing the visual weight and emphasizing the mathematical cadence of the beautifully spaced characters."
  },
  {
    id: "braided-arches",
    titleAr: "و أحسن كما أحسن الله إليك ",
    titleEn: "The Braided Arches - Alhamdulillah",
    subtitleAr: "تصميم كوفي مربع معماري فريد يجسد أية قرآنية من سورة القصص",
    subtitleEn: "Interlocking braided arches ending in 'Alhamdulillah' praise",
    price: 220,
    image: "/images/article_14_1767774568.jpeg",
    category: "luxury",
    size: "52x32 سم",
    limitedEdition: true,
    descriptionAr: "آية «وَأَحْسِنْ كَمَا أَحْسَنَ اللَّهُ إِلَيْكَ» من سورة القصص تتجسد في أقواس كوفية تربيعية صاعدة ومتداخلة تتشابك عند قممها، وتنتهي في قاعدة اللوحة بكتلة واضحة تقرأ «الحمد لله»، في ربط لغوي بين الإحسان والشكر.",
    descriptionEn: "Ascending Square Kufic arches that braid and interlock at their peaks, resolving cleanly at the base of the canvas into a readable block spelling 'Alhamdulillah', hand-painted in gold lacquer on deep black.",
    essayTitleAr: "أقواس صاعدة تنتهي بكتلة 'الحمد لله': حين يتحول التعشيق الكوفي إلى قراءة في القاعدة",
    essayTitleEn: "Ascending Braided Arches Resolving into 'Alhamdulillah': When Interlocked Kufic Becomes a Reading",
    spiritualAr: "تلتقي الأقواس الصاعدة لتصنع تمازجاً روحياً متواصلاً يعبّر عن الارتقاء بالحمد والتسبيح كقوة نورانية ممتدة تملأ الآفاق. تزيّن هذه التحفة المنزل بروح الصفاء والرضا الدائم، مذكرة بأهمية الشكر كصلة وثيقة ومستديمة مع فيض الرزق والنعم العظيمة التي تحف السائلين.",
    spiritualEn: "Ascending calligraphic arches braid together to generate a continuous visual flow, symbolizing the eternal elevation of praise from earth to heaven. This gold-lacquered sculpture instills an atmosphere of deep-seated gratitude and positive visual balance in modern living spaces.",
    geometricAr: "يتميز هذا العمل بتراكيب قوسية متداخلة يدوياً بدقة هندسية بالغة الصعوبة. تتلامس الحروف الكوفية المربعة عند زوايا الدوران لتكوين أشكال هندسية متطابقة، لتستقر بوزن بصري متوازن يسفر في نهايته بأسفل اللوحة عن عبارة الحمد الشريفة والوافرة.",
    geometricEn: "A highly experimental layout featuring looping, overlapping arches created with absolute mathematical resolution. The letters touch gracefully at key rotating nodes, maintaining pure spacing and terminating in a beautifully stable block reading 'Alhamdulillah' at the base plane."
  },
  {
    id: "harmony-of-goodness",
    titleAr: "لا  إله إلا الله  ",
    titleEn: "The Harmony of Doing Good - Wa Ahsinoo",
    subtitleAr: "تكوين معاصر تركيب التوحيد  بألوان زاهية وخطوط كوفية",
    subtitleEn: "'Indeed, Allah loves the doers of good' in colorful abstract design",
    price: 170,
    image: "/images/article_15_1998879702.jpeg",
    category: "lettering",
    size: "43x43 سم",
    limitedEdition: true,
    descriptionAr: "شهادة «لا إله إلا الله» مكتوبة في صفوف كوفية تربيعية متوازنة، في تكوين معاصر يجسد التوحيد بخطوط كوفية متناغمة تحقق توازناً بصرياً راسخاً.",
    descriptionEn: "'Wa ahsinoo inna Allaha yuhibb al-muhsineen' written in Square Kufic rows using cobalt blue, burnt orange, and bright yellow on black, each color occupying distinct horizontal bands to create a vibrant layered composition.",
    essayTitleAr: "كوبالت وبرتقالي وأصفر: 'وأحسنوا' في شبكة كوفية ثلاثية الألوان",
    essayTitleEn: "Cobalt, Orange, and Yellow: 'Wa Ahsinoo' in a Three-Color Square Kufic Grid",
    spiritualAr: "تؤكد الآية الكريمة 'وأحسنوا إن الله يحب المحسنين' أن الإحسان هو ذروة الجمال والسلوك الإنساني الذي يعمر الكون بالمحبة والسلام. تنبثق ألوان اللوحة المتناسقة الزاهية لتبث طاقة الحيوية والتفاؤل والرحمة، جاعلةً الفراغ محراباً للذكر الهادئ والإيجابية والوئام الوجداني الراقي والمتميز.",
    spiritualEn: "The core truth of 'And do good; indeed, Allah loves the doers of good' holds the key to cosmic peace and harmony. Expressed through brilliant modern cobalt-blue and hot orange bands, this design charges the home environment with positive energy, hope, and visual warmth.",
    geometricAr: "جرى بناء هذه اللوحة المعاصرة بنسق خطي أفقي تربيعي دقيق للغاية وتتدفق في ثناياه ألوان النيل الأزرق والبرتقالي الغني. تم احتساب سمك الحروف والفتحات الموازية يدويًا بمسافات متطابقة لإبراز حدة الزوايا وتناسق التباين اللوني اللامع بجودة يدوية شاهقة وفريدة من نوعها.",
    geometricEn: "Engineered with outstanding linear harmony, this design groups the charity verse in stylized colorful grids. Using vibrant blocks of indigo blue and warm sunset saffron, the spacing matches the line widths, ensuring clean geometric legibility and striking color theory."
  },
  {
    id: "rotating-testimony",
    titleAr: "سورة الإخلاص ",
    titleEn: "The Royal Blue Rotating Testimony",
    subtitleAr: "سورة الإخلاص بالكتابة التربيعية الكوفية المعاصرة ",
    subtitleEn: "Symmetric 4-way rotating calligraphy on deep navy blue",
    price: 250,
    image: "/images/article_16_1326328359.jpeg",
    category: "geometric",
    size: "53x34 سم",
    limitedEdition: true,
    descriptionAr: "«سورة الإخلاص» كاملة موزعة في تناظر رباعي الاتجاهات حول محور دائري في المركز، كل ربع يعكس الآخر بدقة، في تكوين كوفي معاصر يدور بآيات التوحيد حول محور اليقين الثابت.",
    descriptionEn: "The Shahada arranged in perfect 4-way rotational symmetry around a central crimson circular pivot on deep navy blue background, each quarter mirroring the other with precise mathematical accuracy.",
    essayTitleAr: "الشهادة رباعية التناظر: أربع نسخ كوفية تدور حول محور قرمزي على الكحلي الأزرق",
    essayTitleEn: "4-Way Rotational Shahada: The Holy Testimony Around a Crimson Axis on Deep Navy Blue",
    spiritualAr: "تدور الأفلاك والخلائق في طواف أبدي مستمر يسبح بحمد الله وعظمته. يرسخ هذا العمل حقيقة الشهادة الخالدة بملمس رباعي الدوران، يلتف حول مركز قرمزي يعبر عن بؤرة الوجود وعلم اليقين الدائم، باعثاً في الأرجاء طمأنينة فائقة وهدوءاً وسكينة تامة تريح الروح المطمئنة بنور الحق الخالد.",
    spiritualEn: "The universe orbits in eternal adoration around the absolute oneness of the Supreme Creator. This quad-rotational symmetry model of the Holy Testimony circles a vibrant crimson focal hub, expressing the perpetual diffusion of divine light, radiating endless stability and deep protective solace.",
    geometricAr: "صُمم هذا العمل الرائد رباعي التناظر بمجموعات مصفوفة بنسبة تماثل كاملة حول نقطة مركزية كقاعدة ارتكاز. المربع الخطي يتبع قواعد حسابية دقيقة لمكعب الكوفي التربيعي، مما يصنع ميزاناً حركياً متكاملاً يتحدث فيه الفراغ السلبي بنفس الجاذبية والوقار ليد الفنان المتقنة.",
    geometricEn: "This avant-garde creation employs strict 4-way rotational symmetry around a centered red circular quadrant. The letter forms are calibrated to maintain equal stroke widths and void ratios, resulting in a mesmerizing kinetic tension that balances the visual fields perfectly."
  },
  {
    id: "ayat-al-kursi-blue",
    titleAr: "آيات من سورة المزمل",
    titleEn: "The Throne Verse Sanctuary - Ayat Al-Kursi",
    subtitleAr: "٤ آيات من سورة المزمل في شكل زخرفي يجسد صومعتين إسلاميتين ",
    subtitleEn: "A grand horizontal representation of the Throne Verse on blue velvet",
    price: 330,
    image: "/images/article_17_1677164094.jpeg",
    category: "geometric",
    size: "58x41 سم",
    limitedEdition: true,
    descriptionAr: "أربع آيات من سورة المزمل مكتوبة بالخط الكوفي المربع في أعمدة رأسية متوازية ومتراصة، مرسومة يدوياً، في تكوين زخرفي يجسد صومعتين إسلاميتين ويربط بين هدوء الليل ونداء «يا أيها المزمل».",
    descriptionEn: "The complete Ayat Al-Kursi (Quran 2:255) written in Square Kufic arranged in tight parallel vertical columns, hand-painted in layered gold acrylics on a deep royal indigo-blue background canvas.",
    essayTitleAr: "آية الكرسي كاملة في أعمدة ذهبية متوازية: حجة الحفظ الإلهي على الإنديغو الملكي",
    essayTitleEn: "The Entire Ayat Al-Kursi in Parallel Gold Columns: The Throne Verse as a Monumental Protective Grid on Indigo",
    spiritualAr: "تعد آية الكرسي أعظم آية في كتاب الله الشريف، وتفيض بآيات الحفظ والولاية المطلقة والملك العظيم. صُممت اللوحة كصرح حروفي مهيب لتبث حماية سماوية وبركة دافئة تعمر البيت، جاعلةً مساحتكم ركناً للطمأنينة الكاملة واليقين الراسخ بنفحات الحماية والرضوان على مر السنين.",
    spiritualEn: "Recognized as the most powerful protective text in the Holy Quran, Ayat Al-Kursi embodies supreme divine sovereignty and limitless guardianship. Structured as a grand calligraphic palace, this artwork covers your home with spiritual protection, peace, and sacred power.",
    geometricAr: "بناء خطي معماري بالغ الطول والارتفاع، ترتصف فيه كلمات آية الكرسي كاملة في أعمدة رأسية متراصة ومذهبة ببريق اللون الذهبي الفاخر الموزع. الخلفية الكحلية الزرقاء تمنح اللوحة عمقاً بصرياً يحاكي سموات الحفظ والجمال الكلاسيكي العظيم، محققة ميزاناً تشكيلياً هندسياً فريداً.",
    geometricEn: "A monumental calligraphic installation organizing the entire Throne Verse into tight parallel columns of geometric stability. Executed in beautiful hand-layered gold acrylics on a rich royal-blue indigo backdrop, it achieves a high-contrast layout that is flat and perfectly legible yet visually deep."
  },
  {
    id: "muzzammil-cloisters",
    titleAr: "سورة الفلق ",
    titleEn: "The Cloistered Light - Ya Ayyuha Al-Muzzammil",
    subtitleAr: "تجسد سورة الفلق في مربع يقتضي اللون الأسود و البرتقالي و الأحمر  ",
    subtitleEn: "Twin elegant arches featuring 'Ya Ayyuha Al-Muzzammil'",
    price: 280,
    image: "/images/article_18_133853991.jpeg",
    category: "luxury",
    size: "47x47سم",
    limitedEdition: true,
    descriptionAr: "«سورة الفلق» كاملة مكتوبة بالخط الكوفي المربع داخل مربع في هيكل ثنائي الأقواس المئذنية، في تكوين يجسد الحماية الإلهية ويعكس بنية الفلق الصاعد في عمارة كوفية متناظرة.",
    descriptionEn: "'Ya ayyuha al-muzzammil' written in Square Kufic inside twin minaret-shaped arch pillars, with the text in coral-rust orange and precise gold border accents on deep black background.",
    essayTitleAr: "قبتان مئذنيتان للمزمل: 'يا أيها المزمل' في هيكل كوفي برتقالي مرجاني وذهبي",
    essayTitleEn: "Twin Minaret Arches for the Wrapped Prophet: 'Ya Ayyuha Al-Muzzammil' in Coral-Orange Square Kufic",
    spiritualAr: "يوقظ النداء الكريم 'يا أيها المزمل' في النفس الشوق لمناجاة الخالق والتدبر الصافي في هدوء الليل وسكينته الكبرى. تجسد هذه التحفة طاقة التهجد والسلام المطلق، لتملأ مساحتكم بعبير من السكينة الروحية والدعاء المستجاب والارتقاء الوجداني الخالص لمحسن نصائيبة.",
    spiritualEn: "The divine proclamation calling 'O you who wraps himself...' invokes a deep longing for quiet night prayer and supreme spiritual contemplation. This duo-arch tapestry infuses any space with absolute silence, meditative depth, and continuous domestic harmony.",
    geometricAr: "لوحة محرابية متميزة ثنائية الأقواس ترتكز على أساس خطي متناسق الأبعاد. تداخلت الحروف ونقاط الحركات الهندسية باللون البرتقالي الساحر والذهب الفاخر، مما يبرز الدقة الرياضية في عمارة المساجد والتقسيم الهندسي المتناسق لخطوط الكوفي التربيعي المأثور بعبق التراث الأصيل.",
    geometricEn: "Designed with twin minaret-like vertical structures, this layout frames the sacred text inside highly defined curves. The meticulous hand-painted details use a custom palette of brilliant gold and fiery coral-rust orange, maintaining perfect structural balance between white elements and deep voids."
  },
  {
    id: "qul-protection-grid",
    titleAr: "الكلمة الطيبة صدقة ",
    titleEn: "The Red 'Qul' - Surah of Protection",
    subtitleAr: "لوحة زرقاء  تجسد زخرفة لعبرة قديمة ",
    subtitleEn: "Bespoke black & gold grid on white canvas with red accent",
    price: 280,
    image: "/images/article_19_1856483579.jpeg",
    category: "geometric",
    size: "53x41 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «الكلمة الطيبة صدقة» تجسد الحكمة النبوية في شبكة كوفية مربعة، مع إبراز كلمة الافتتاح داخل مربع بارز يحدد نقطة البداية للقارئ، في تكوين يربط بين الكلمة الطيبة والصدقة والجمال الكوفي الناصع.",
    descriptionEn: "Protection verse ('Qul') written as a high-contrast black Square Kufic grid on a clean white canvas, with the opening word 'Qul' prominently framed inside a bold crimson-red square marker to guide the reading.",
    essayTitleAr: "شبكة كوفية سوداء على أبيض بمربع 'قل' الأحمر: تصميم حماية بتباين مطلق",
    essayTitleEn: "Black Square Kufic on White Canvas with a Red 'Qul' Marker: High-Contrast Protection Verse Grid",
    spiritualAr: "تجمع 'قل' المعوذات لتدفع عن النفس الهواجس وتبث طمأنينة تامة تحفظ السكينة واليقين بفضل الله الحفيظ رَب الخلق والبرايا. اللوحة بحدودها البيضاء الناصعة وحرفها الأسود الوقور تبعث طاقة الحماية والبركة وتذكر بمفاتيح التوكل المطلق والسلام الدائم بالقلوب الندية.",
    spiritualEn: "The single command 'Qul' (Say) triggers the ultimate protection verses that clear the mind and shield the home with absolute divine shelter. The design acts as a quiet visual guardian, creating a pure atmosphere of complete security, focus, and visual peace.",
    geometricAr: "تعتمد اللوحة ميزاناً هندسياً ناصع البياض يرتسم عليه شبكة كوفية سوداء شديدة التباين. تتوسط مطلع الآية علامة 'قل' داخل مربع بلون أحمر ياقوتي قرمزي دافئ، مما يسحب انتباه العين مباشرة نحو نقطة الارتكاز ويحقق توازناً في تصفيف الخطوط المتعامدة الفريد.",
    geometricEn: "Presenting a high-contrast black grid layout over a crystalline white backdrop, this square canvas is balanced by a prominent ruby-red square encasing the word 'Qul'. This strategic pop of warm color establishes an elegant visual hierarchy and highlights the mathematical grid rules."
  },
  {
    id: "three-minarets-testimony",
    titleAr: "آيات من سورة الرعد ",
    titleEn: "The Three Minarets - La ilaha illa Allah",
    subtitleAr: " وَكُلُّ شَيْءٍ عِندَهُ بِمِقْدَار* عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ ",
    subtitleEn: "Triple-arch braided vertical calligraphy on royal blue background",
    price: 250,
    image: "/images/article_20_1598895584.jpeg",
    category: "luxury",
    size: "51x39 سم",
    limitedEdition: true,
    descriptionAr: "آيات من سورة الرعد — «وَكُلُّ شَيْءٍ عِندَهُ بِمِقْدَار* عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ» — مشكّلة في ثلاثة أعمدة كوفية رأسية تتعشق وتتضفر عند قممها، مستحضرةً صورة المآذن وعظمة علم الله وقدرته.",
    descriptionEn: "'La ilaha illa Allah' shaped into three vertical Square Kufic columns that braid and interlock at their peaks, rising on a deep royal indigo blue background in an evocation of classic Islamic minaret forms.",
    essayTitleAr: "ثلاثة أعمدة كوفية ذهبية تتعشق في القمة: 'لا إله إلا الله' كمآذن رأسية على الإنديغو",
    essayTitleEn: "Three Braided Gold Spires: 'La ilaha illa Allah' as Triple Minarets Rising on Royal Indigo",
    spiritualAr: "تتسامق صاعدات اللوحة مذهبة لتشير لتوحيد الله الخالق الأحد، راسمة مشهداً يفيض بجلال المآذن والمحاريب التي تنطلق منها الشهادة المباركة نحو السموات العلا. تبعث اللوحة في الفراغ طاقة النقاء والارتقاء الروحي، محولة الجدران إلى محراب دائم من السكينة التامة.",
    spiritualEn: "The vertical lines of this sculpture ascend to celebrate absolute monotheism, reminding the soul of tall spiritual minarets echoing with holy prayers. This vertical masterpiece infuses any luxury drawing room with themes of hope, moral strength, and continuous devotion.",
    geometricAr: "ثلاثة أقواس ورأسيات مئذنية معشقة ومبنية يدوياً بنسب رياضية بالغة الصرامة. تخرج الحروف المذهبة بنقاء بائن على خلفية زرقاء مريحة للعين ومعقمة بالأبعاد الهندسية التي تظهر تزاوجاً مستقراً متناسق الحركة بمقاييس الكوفي التربيعي المتناظر.",
    geometricEn: "Based on an asymmetrical triple-arch configuration, this tall vertical artwork braids three long columns at the peaks. Hand-painted with rich metallic gold leaf on deep cobalt velvet, it exhibits exceptional line resolution and provides a majestic, tall spatial presence."
  },
  {
    id: "walidayn-sanctuary",
    titleAr: "النجمة الثمانية الكوفية",
    titleEn: "Parental Sanctuary - Wa Bil Walidayni",
    subtitleAr: "تصميم متناظر رائع بقلب أحمر",
    subtitleEn: "Beautiful Kufic composition of parent respect under golden dome",
    price: 150,
    image: "/images/article_21_1425388259.jpeg",
    category: "geometric",
    size: "43x43 سم",
    limitedEdition: true,
    descriptionAr: "«النجمة الثمانية الكوفية» بُنيت من حروف الخط الكوفي المربع، تتقاطع أضلاعها الثمانية حول نقطة مركزية في قلب اللوحة، في تصميم متناظر رائع يجسد التوحيد كنجم كوفي دوار.",
    descriptionEn: "'Wa bil-walidayni ihsana' written in Square Kufic beneath a warm orange double-bordered horizontal arch dome, with gold and orange letters on deep black background.",
    essayTitleAr: "'وبالوالدين إحسانا' تحت قبة أفقية برتقالية: بر الوالدين في قوس كوفي دافئ",
    essayTitleEn: "'Wa Bil-Walidayni Ihsana' Under an Orange Horizontal Arch: Filial Piety in a Warm Kufic Dome",
    spiritualAr: "بر الوالدين هو وصية الله العظمى وطريق نيل البركات والسعادة الزوجية وسكينة الأبناء وجنتهم الطيبة. صممت هذه التحفة وتحفها قبة السلام لتكون رداء وخطاب مودة يزين البيت، مستحضراً طاقة الوفاء الدائم ولم شمل الأسرة والهدوء والانسجام النفسي الكامل.",
    spiritualEn: "Honor to parents is the ultimate moral duty and the core pathway to divine blessing and family bliss. Housed beneath a protective horizontal gold dome, this calligraphy invokes beautiful warmth, filial respect, and lifelong domestic harmony within your household.",
    geometricAr: "اللوحة ممتدة أفقياً بميزان خطي كوفي مربع غاية في الرصانة، حيث تلتف عبارة 'وبالوالدين إحسانا' تحت قوس أفقي ذو انحناءات متناظرة ومبنية يدوياً بدقة وتلوينات برتقالية ناعمة متناسقة مع طبقات الذهب والبلور الأثري المحكم الفخامة.",
    geometricEn: "Extending horizontally over a grand parallel scale, the letters flow seamlessly under a stylized double-bordered orange arch. The contrast between curved containment lines and vertical block structures illustrates the artist's expertise in combining geometric stability with flowing visual themes."
  },
  {
    id: "octagonal-star-kufic",
    titleAr: "قُلْ إِنَّ رَبِّي يَبْسُطُ الرِّزْقَ لِمَن يَشَاءُ وَيَقْدِرُ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ",
    titleEn: "The Eight-Pointed Kufic Star",
    subtitleAr: "سورة سبإ - الآية 36",
    subtitleEn: "Symmetric octagonal design with central crimson core",
    price: 220,
    image: "/images/article_22_2094686485.jpeg",
    category: "geometric",
    size: "61x47 سم",
    limitedEdition: true,
    descriptionAr: "آية «قُلْ إِنَّ رَبِّي يَبْسُطُ الرِّزْقَ لِمَن يَشَاءُ وَيَقْدِرُ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ» من سورة سبأ مكتوبة في نجمة ثمانية الأضلاع من الخط الكوفي المربع، تتقاطع أضلاعها حول نقطة مركزية في قلب التكوين.",
    descriptionEn: "An 8-pointed star built from Square Kufic letter strokes in rich gold, with eight geometric blades crossing at a prominent central crimson focal point on a deep black background.",
    essayTitleAr: "النجمة الكوفية ثمانية الأضلاع: حروف ذهبية تتقاطع لتلتقي في مركز أحمر قرمزي",
    essayTitleEn: "The Eight-Pointed Kufic Star: Gold Letter Strokes Crossing to a Crimson Center",
    spiritualAr: "تجسد النجمة الثمانية الكوفية حقيقة النور والجمالية الكونية الدوارة في الموروث الشرقي، حيث تدور التسبيحات والشهادة حول مبدأ التوحيد الثابت والأزلي لله الأحد الصمد لتبث ومضات من الدفء والسكينة والوقار بقلوب مقتنيها.",
    spiritualEn: "The calligraphic octational star maps out the celestial order of cosmic praise, revolving in infinite harmony around the divine point of oneness. Highlighting a warm red core, this gold star introduces elegant tranquility, cultural gravity, and intellectual depth to your home.",
    geometricAr: "شبكة هندسية فائقة التعقيد تجمع بين تقاطع ثمانية أضلاع رياضية متناظرة. جرى رسم الحواف بالخط الكوفي المربع يدوياً بكل دقة، متناسقة ببريق الذهب مع اللون الأحمر القرمزي المتواجد بالقلب، لتمنح اللوحة ميزاناً فريداً يحترم دقة المربع الكوفي.",
    geometricEn: "This geometric star is mathematically engineered inside an 8-axis symmetry grid. The gold leaf borders encasing each calligraphic line are hand-drawn to frame a prominent central red point, resolving radial forces and establishing absolute architectural stability."
  },
  {
    id: "azure-path-forgiveness",
    titleAr: "مَن قامَ رَمَضانَ إيمانًا واحتِسابًا غُفِرَ له ما تَقدَّمَ مِن ذَنبِه",
    titleEn: "The Azure Path of Forgiveness",
    subtitleAr: "الراوي : أبو هريرة | المحدث : البخاري | المصدر : صحيح البخاري",
    subtitleEn: "Horizontal calligraphy in celestial blue and gold borders",
    price: 220,
    image: "/images/article_23_538742443.jpeg",
    category: "geometric",
    size: "53x47 سم",
    limitedEdition: true,
    descriptionAr: "حديث «مَن قامَ رَمَضانَ إيمانًا واحتِسابًا غُفِرَ له ما تَقدَّمَ مِن ذَنبِه» مكتوب بالخط الكوفي المربع في تكوين أفقي مع حدود دقيقة، يربط بين قيام رمضان والمغفرة والنقاء الروحي.",
    descriptionEn: "'Wa sari'oo ila maghfirating min rabbikum' written in Square Kufic in deep azure and cobalt blue on a clean white background with delicate gold-leaf borders, designed to harmonize with minimalist modern interiors.",
    essayTitleAr: "الكوبالتي والأزرق الفيروزي على أبيض: 'وسارعوا إلى مغفرة' بخط كوفي نظيف للفضاء العصري",
    essayTitleEn: "Cobalt and Azure on White: 'Wa Sari'oo ila Maghfira' in Clean Kufic for Minimalist Spaces",
    spiritualAr: "نداء المغفرة والسباق نحو الرضوان والجنة يفتحان للروح طاقات لامتناهية من الأمل للتجدد والتسامي عن الخطايا. يجسد هذا العمل النقاء السماوي بلمسات زرقاء ساطعة تلج القلوب، ناشرة سكينة وافرة وسكينة عظيمة مفعمة بالتسامح الإنساني الإيجابي.",
    spiritualEn: "The calling to speed towards forgiveness reveals infinite vistas of hope and spiritual rejuvenation. Colored in soft небе-azure hues on minimum white, this composition reflects heavenly clear lights, guiding the mind with peace, trust, and absolute divine protection.",
    geometricAr: "لوحة أفقية ممتدة تم توزيع خطوطها الكوفية التربيعية بطريقة تضمن التوازن الرياضي المتكامل للفراغات. تحف التكوين شواهد مذهبة دقيقة تم تلوينها يدوياً لتنسجم الألوان الفيروزية والزرقاء مع خلفية العمل الناصعة لتعزز التباين والجمال البصري.",
    geometricEn: "Designed as a minimal horizontal script, this canvas aligns the characters within a perfectly calculated space. Vibrant sky-blue and cobalt pigments harmonize with delicate gold-leaf borders on clean canvas, resulting in a design that fits beautifully inside minimalist modern interiors."
  },
  {
    id: "ramadan-lights-lights",
    titleAr: "سورة الكوثر",
    titleEn: "The Ramadan Stand - Man Qama Ramadan",
    subtitleAr: "سورة الكوثر بالكتابة التربيعية الكوفية ",
    subtitleEn: "Elegant purple double-minaret structure celebrating Ramadan",
    price: 250,
    image: "/images/article_24_1507137126.jpeg",
    category: "lettering",
    size: "47x41 سم",
    limitedEdition: true,
    descriptionAr: "«سورة الكوثر» كاملة مكتوبة بالخط الكوفي التربيعي داخل مئذنتين متوازيتين، في تكوين يحتفي بسورة النعيم الأبدي ويجسدها في عمارة كوفية شامخة.",
    descriptionEn: "The hadith 'Man qama Ramadan imanan wa ihtisaban ghufira lahu ma taqaddama min dhanbihi' written in Square Kufic inside twin parallel minaret structures in royal violet-purple with brilliant gold-leaf crowns on black.",
    essayTitleAr: "حديث قيام رمضان في مئذنتين بنفسجيتين: الخط الكوفي المذهب يحتفي بالشهر الفضيل",
    essayTitleEn: "The Ramadan Prayer Hadith in Twin Violet Minarets: Gold-Crowned Square Kufic Celebrating the Holy Month",
    spiritualAr: "قيام رمضان هو بوابة الغفران ونيل البركات والتقرب من الخالق بنقاء وعشق روحي عظيم. يتسامق صرح أنوار رمضان باللون البنفسجي الساحر برداء روحي ملكي ليعيد للذاكرة ليالي السلام والصلوات الدافئة بالمسجد النبوي الشريف المليء بالرحمات.",
    spiritualEn: "The spiritual atmosphere of Ramadan prayers guides the faithful to profound self-reflection and absolute redemption. Rising as twin violet-purple spires with rich gold-leaf crowns, this piece brings the warm glow of holy nights and deep divine blessings directly into your living space.",
    geometricAr: "تم تصميم اللوحة لتجسد مئذنتين متوازيتين من الخط الكوفي التربيعي المتشابك. حطت الألوان البنفسجية الملكية والذهبية البراقة بنسب يدوية محسوبة بدقة متناهية، محققة محاذاة أفقية ورأسية صارمة تماثل شموخ العمارة الإسلامية التاريخية الكبرى.",
    geometricEn: "This layout models classic twin minaret towers made of interlocked Square Kufic calligraphy. Adorned with a royal purple palette and rich gold accents, the vertical grids conform to absolute mathematical ratios, establishing visual elevation and a majestic architectural presence."
  },
  {
    id: "devotion-labyrinth",
    titleAr: "بإسم الله توكلت على الله و لا حول و لا قوة  إلا بالله",
    titleEn: "The Labyrinth of Devotion",
    subtitleAr: "تصميم هندسي متقن",
    subtitleEn: "Bespoke masterwork grid accented with crimson vowels",
    price: 280,
    image: "/images/article_25_512021195.jpeg",
    category: "geometric",
    size: "49x41 سم",
    limitedEdition: true,
    descriptionAr: "عبارة «بإسم الله توكلت على الله و لا حول و لا قوة إلا بالله» منسوجة في شبكة كوفية مربعة دقيقة بتراكب حروفي معقد، مزينة بنقاط تشكيل توزع على الحروف وفق النظام النحوي الكوفي القديم، في تكوين يجسد التوكل واليقين.",
    descriptionEn: "A complex interlocked Square Kufic grid of dhikr and praises in gold on black, decorated with precisely placed ruby-red vowel dots that follow the ancient Kufic grammatical notation system.",
    essayTitleAr: "شبكة أذكار كوفية بنقاط تشكيل حمراء: المخطوطة الأثرية تلتقي بالهندسة المعاصرة",
    essayTitleEn: "Kufic Dhikr Grid with Ancient Red Vowel Dots: Manuscript Grammar Meets Contemporary Geometry",
    spiritualAr: "يمثل البحث في متاهة الحروف والذكر والآيات رحلة المتعبد الطامح للوصول لجلال الحق وهدائه الصافي. تمنح هذه اللوحة المتأمل عمقاً روحياً يدعوه لقراءة التفاصيل والوقوف عند جمال التسبيح والحمد، ناشرةً حماية وافرة وطاقة سكينة هادئة بالمنزل.",
    spiritualEn: "The path of seeking truth mimics a beautiful visual labyrinth where every turn reveals a hidden prayer of praise. This interlocked Square Kufic grid dotted with ruby vowels coordinates custom protective energies, establishing a serene anchor of continuous mindfulness and blessing.",
    geometricAr: "تراكب حروفي دقيق للمربع التربيعي يضم تسبيحات في شبكة معقدة بنسبة تماثل 1:1 كاملة. تم وضع نقاط الحروف (الحركات الكوفية الأثرية) باللون الأحمر الياقوتي لسهولة فك التداخل الهندسي ولتحقيق تباين بصري يسحر الألباب لجمال الخط العربي والزخرفة.",
    geometricEn: "This highly detailed 1:1 square calligraphic grid represents complete mathematical structure. The character arrays are neatly dotted with deep ruby vowels that reference ancient calligraphic manuscripts, neutralizing visual density and highlighting straight 90-degree corners with majestic precision."
  },
  {
    id: "twin-pillars-ruby",
    titleAr: "فَتَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ",
    titleEn: "The Twin Pillars and the Ruby",
    subtitleAr: "سورة المؤمنون الآية ١٤ ",
    subtitleEn: "A magnificent dual-pillar Kufic painting on blue canvas",
    price: 300,
    image: "/images/article_26_1399227940.jpeg",
    category: "luxury",
    size: "68x41 سم",
    limitedEdition: true,
    descriptionAr: "آية «فَتَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ» من سورة المؤمنون مكتوبة في عمودين كوفيين رأسيين متناظرين، تتوسطهما نقطة ارتكاز بصرية مرسومة يدوياً، في تكوين يمجّد إبداع الخالق بأحسن الخلق.",
    descriptionEn: "Twin symmetrical vertical Square Kufic gold columns bearing the name of Allah and the Shahada on deep royal indigo, centered by a hand-painted ruby red gemstone that serves as the mathematical focal point of the composition.",
    essayTitleAr: "عمودان ذهبيان وياقوتة حمراء على الإنديغو: اسم الجلالة والشهادة في محور بصري متوازن",
    essayTitleEn: "Twin Gold Columns and a Ruby Gem on Indigo: The Name of Allah and Shahada Around a Crimson Focal",
    spiritualAr: "تنتصب المنارتان كأعمدة شاهقة من الذهب والوقور تشير لعظمة اسم الجلالة المبارك وعظمة الوحدانية. يتوسط التكوين ياقوتة حمراء تبرز مركزية النور الطاهر والدفء بقلب المؤمن، لتغمر هذه اللوحة الفخمة أي فراغ بطاقة السكينة والأمان والبركات والأنوار الإلهية الدائمة.",
    spiritualEn: "Standing tall as twin structures of gilded sacred geometry, this artwork invokes the ultimate presence of divine majesty and cosmic balance. Centered with a warm crimson gemstone, it channels a protective hearth of focus, light, and visual quietude into high-end interiors.",
    geometricAr: "تصميم ثنائي الأعمدة الكوفية المتطابقة بنسبة تماثل كاملة ومتناهية الدقة تم طلاؤها بماء الذهب المطلي ببريق دافئ. تتربع الياقوتة المضيئة بوسط السجادة الزرقاء الملكية لتظهر تمازج الألوان وعمق الشبكة التربيعية الكوفية التي توازن الكتل والفرغات في سكون كوفي تربيعي دقيق.",
    geometricEn: "This layout introduces twin parallel Kufic columns built with symmetric precision. The letter edges are meticulously hand-painted in gold acrylics over deep royal indigo linen, highlighting a vibrant ruby gemstone at the mathematical center to resolve visual paths elegantly."
  },
  {
    id: "muddaththir-arches",
    titleAr: "سورة القدر ",
    titleEn: "The Clothed Messenger - Ya Ayyuha Al-Muddaththir",
    subtitleAr: "آيات سورة القدر بالكتابة الكوفية التربيعية ",
    subtitleEn: "Twin elegant arches featuring 'Ya Ayyuha Al-Muddaththir'",
    price: 350,
    image: "/images/article_27_801957079.jpeg",
    category: "luxury",
    size: "49x49 سم",
    limitedEdition: true,
    descriptionAr: "«سورة القدر» كاملة مكتوبة بالخط الكوفي التربيعي داخل قبتين محرابيتين متناظرتين، في تكوين يحتفي بليلة القدر ويجسد بركتها في عمارة كوفية مزدوجة القباب.",
    descriptionEn: "'Ya ayyuha al-muddaththir' written in Square Kufic inside twin symmetrical arch domes in vibrant sunset orange, surrounded by professional double-line gold border trims on black background.",
    essayTitleAr: "قبتان محرابيتان لـ'يا أيها المدثر': البرتقالي البديع وحدوده الذهبية المزدوجة",
    essayTitleEn: "Twin Arch Domes for 'Ya Ayyuha Al-Muddaththir': Sunset Orange Kufic with Double Gold Borders",
    spiritualAr: "يحمل النداء السماوي الجليل 'يا أيها المدثر' معاني المسؤولية والنهوض بالخير ونشر المحبة والسلام للبشرية جمعاء. صُممت اللوحة بأقواسها المعشقة لتكون رمزاً للأمان واليقين، تدعو للطمأنينة الكاملة والارتقاء الروحي، وتغمر بيتكم بالطاقة الإيجابية وبركات السلام الروحي المستدام.",
    spiritualEn: "The sacred call to 'O you who covers himself...' represents the dawn of divine guidance and a powerful awakening of moral duty. Enclosed within beautiful twin arches of shimmering gold leaf, this artwork introduces themes of peaceful sanctuary, inner strength, and endless domestic luck.",
    geometricAr: "تكوين معماري استثنائي يضم لوحة محرابية ثنائية القباب تسير فيها الحروف الكوفية بدقة وهندسة خلاقة. ينساب الحرف البرتقالي البديع كمنار فني مبرزاً الأبعاد والظلال، مع حفر التفاصيل والخطوط لتتسق بروعة مع الإطارات الذهبية المحكمة والمصاغة يدوياً باحترافية تامة لجمال كلاسيكي باقٍ.",
    geometricEn: "Architecturally structured with a twin-arched dome layout, this composition displays the characters in horizontal and vertical configurations of high rigor. Using warm terracotta-orange and bright gold paints, the line-to-void spacing is kept uniform, highlighting the artist's ability to curve grid systems gracefully."
  },
  {
    id: "pavilion-truth-peace",
    titleAr: "الحمدلله الذي أحصى كل شيء عدداً، وجعل لكلّ شيء أمداً، ولا يشرك في حكمه أحداً",
    titleEn: "The Pavilion of Truth & Peace",
    subtitleAr: "لوحة ذات خط تربيع  كوفي تحتوي جل عبارات الحمد و الشكر ",
    subtitleEn: "Symmetric square calligraphy framed with a striking red border",
    price: 300,
    image: "/images/article_28_974105925.jpeg",
    category: "geometric",
    size: "68x43 سم",
    limitedEdition: true,
    descriptionAr: "آية «الحمدلله الذي أحصى كل شيء عدداً، وجعل لكلّ شيء أمداً، ولا يشرك في حكمه أحداً» مكتوبة في حروف كوفية تربيعية داخل إطار مربع متناظر، يقف على يمينها عمود مستطيل صلب يمتد طولياً كعلامة بصرية توازن ثقل الشبكة الأفقية، في تكوين يجسد الحمد والحكمة الإلهية.",
    descriptionEn: "Perfectly symmetrical Square Kufic gold characters inside a square frame, with a solid full-height crimson column on the right edge acting as a dominant vertical accent that balances the weight of the horizontal grid.",
    essayTitleAr: "شبكة كوفية مربعة وعمود قرمزي شاهق: ثنائية التناظر والتباين في لوحة مربعة",
    essayTitleEn: "Symmetric Kufic Square and a Full-Height Crimson Column: Visual Contrast and Grid Equilibrium",
    spiritualAr: "يحث الصدق على بناء علاقات متينة راسخة ويمهد للسلام الداخلي والأمن النفسي بكل قلب. تتميز هذه اللوحة بجاذبية فائقة وقوة روحية تحمي الفراغ، من خلال تباين حرفها الأسود والمربع القرمزي الذي يمثل منار اليقين وبوصلة الطهارة التي تنور أرجاء المكان بالفخامة والوقار والبركات.",
    spiritualEn: "Absolute truth and integrity establish an unyielding foundation for inner peace and mental clarity. Styled with contrast-rich black grid rows and balanced by a striking crimson accent column, this piece functions as a celestial compass, promoting moral clarity and focused stillness.",
    geometricAr: "توازن هندسي رفيع تجمع فيه اللوحة بين خطوط أفقية ورأسية متناهية التناظر داخل إطار مربع محكم. يرتفع عمود مستطيل ياقوتي بالجهة اليمنى ككتلة جاذبة متوازنة تعطي اللوحة ثقلاً فنياً وعمقاً تشكيلياً فريداً يحترم السكون الكوفي والرياضيات الكلاسيكية الطيبة.",
    geometricEn: "Governed by strict line-alignment values, this square composition integrates balanced character paths enclosed in a minimal perimeter. A bold crimson-vertical column highlights the right border, neutralizing the linear horizontal weight and creating an extraordinary visual tension."
  },
  {
    id: "surah-asr-time",
    titleAr: "سبحان الله ",
    titleEn: "Surah Al-Asr - The Flight of Time",
    subtitleAr: "لوحات تشكل نجمة في شكل تسبيح ",
    subtitleEn: "Complete horizontal rendering of Surah Al-Asr beside 'Allah'",
    price: 170,
    image: "/images/article_29_351996719.jpeg",
    category: "geometric",
    size: "49x49 سم",
    limitedEdition: true,
    descriptionAr: "عبارة «سبحان الله» مكتوبة في لوحات تشكل نجمة بالخط الكوفي المربع، تتشابك فيها الحروف في تكوين زخرفي يحوّل التسبيح إلى نجمة كوفية تملأ الفراغ بالذكر والسكينة.",
    descriptionEn: "The complete Surah Al-Asr written in parallel horizontal gold Square Kufic rows, anchored by a tall vertical 'Allah' name block on the left edge, on deep black background.",
    essayTitleAr: "سورة العصر في صفوف ذهبية مع كتلة 'الله' الرأسية: الزمن والتوحيد في لوحة أفقية واحدة",
    essayTitleEn: "Surah Al-Asr in Parallel Gold Rows with a Vertical 'Allah' Block: Time and Oneness in One Horizontal Canvas",
    spiritualAr: "تقسم سورة العصر بالزمن وعمر الإنسان لتوضح معالم الخسارة والربح الحقيقي المبني على الإيمان والعمل الصالح والتواصي بالحق والصبر. صممت هذه التحفة لتكون سياجاً عائلياً وعظياً يبث بركة مباركة ويعيد ترتيب أولويات الساكنين نحو النقاء والصفاء الإيماني والتوكل الشامل والنجاح.",
    spiritualEn: "Declaring the sacred value of time, Surah Al-Asr maps the blueprint of human victory: faith, righteous deeds, and mutual counseling of truth and patience. Displayed in high-end living areas, this Scripture acts as an anchor of divine favor, invoking patience and eternal hope.",
    geometricAr: "لوحة أفقية صخرية مهيبة ترتصف سطورها الكوفية المذهبة وفق هندسة التوازي الشديد والتباين الوافر الحروفي. يستقر لفظ الجلالة 'الله' ككتلة طولية متينة في يسار التكوين ليعود ويلجم الفراغ الأفقي الطويل ويمنح اللوحة وزناً جليلاً وعمارة متكاملة شاهقة الجمال ليد محسن نصائيبة.",
    geometricEn: "A breathtaking horizontal layout mapping the holy verses of Surah Al-Asr in exquisite parallel gold bands. The name 'Allah' is structured as a robust vertical anchor on the left edge, neutralizing the horizontal force vector and ensuring solid calligraphic weight."
  },
  {
    id: "pinwheel-of-praise",
    titleAr: "لا إله إلا الله محمد رسول الله ",
    titleEn: "The Pinwheel of Praise",
    subtitleAr: "لوحة تجسد عبارة التوحيد في شكل زخرفي ملون بالبرتقالي و الأزرق ",
    subtitleEn: "Pinwheel 8-point rotating star calligraphy in gold on black",
    price: 300,
    image: "/images/article_30_1757381349.jpeg",
    category: "geometric",
    size: "56x56 سم",
    limitedEdition: true,
    descriptionAr: "شهادة «لا إله إلا الله محمد رسول الله» مصاغة في تصميم كوفي مربع على شكل دولاب ثماني المحاور، تنطلق فيه شفرات الحروف من المركز في ثمانية اتجاهات متساوية، في زخرفة تجسد التوحيد كحركة دورانية أبدية.",
    descriptionEn: "A Square Kufic design in gold shaped as an 8-axis rotating pinwheel, with calligraphic blades radiating outward from the center in eight equal directions on deep black, simulating spinning rotational movement.",
    essayTitleAr: "الدولاب الكوفي الذهبي الثماني المحاور: حروف تدور في ثمانية اتجاهات على الأسود",
    essayTitleEn: "The 8-Axis Gold Kufic Pinwheel: Calligraphic Blades Radiating in Eight Directions on Black",
    spiritualAr: "يتهجى الكون بأسره حمد الله وتسبحه في دوران أبدي يثير الدهشة والتدبر الديني الصافي بالقلب. تعيد هذه النجمة الثمانية الدوارة صياغة هذا الطواف اللامحدود داخل ميزان كوفي يفيض بالحركة، باعثاً في الأرجاء طاقة مفعمة بالتفاؤل الإيماني والسلام النفسي والأمان الروحي للروح الطيبة.",
    spiritualEn: "The entire cosmos participates in a perpetual dance of divine praise, revolving in absolute harmony. Reinterpreting this cosmic orbit inside an 8-sided dynamic calligraphic star, this work introduces high-vibrational peace, joy, and deep meditative focus into private studies.",
    geometricAr: "تم تصميم اللوحة بنسق فريد يمثل نجمة ثمانية مستوحاة من فكرة الدولاب والرياح الدوارة. تلتقي أطراف الخطوط الكوفية التربيعية لتشكل مروحة بصرية مذهبة بنقاء على خلفية داكنة، محققة توازناً طريفاً وجميلاً متكاملاً مع قوانين التناظر الرياضية للكوفي المربع.",
    geometricEn: "Rigorously engineered as an 8-axis rotational kinetic star, this layout simulates the movement of a dynamic pinwheel. The letters align symmetrically to establish balanced angular blades, achieving a highly distinct blend of fluid visual movement and strict orthographic stillness."
  },
  {
    id: "cosmic-wheel-adoration",
    titleAr: "سورة الناس ",
    titleEn: "The Cosmic Wheel of Adoration",
    subtitleAr: "عمل فني فاخر يجسد سورة الناس ",
    subtitleEn: "A magnificent cosmological composition on obsidian background",
    price: 200,
    image: "/images/article_31_467106903.jpeg",
    category: "luxury",
    size: "50x50 سم",
    limitedEdition: true,
    descriptionAr: "«سورة الناس» كاملة مكتوبة في عجلة هندسية كونية ببؤرة دائرية في المركز، تحيط بها أربعة أركان في الزوايا، في عمل فني فاخر يجسد سورة الحفظ الأخيرة ويدور بآياتها حول مركز اليقين.",
    descriptionEn: "A cosmological geometric wheel with a central cobalt-turquoise circular core bearing the word of monotheism, surrounded by four symmetrically placed gold corner blocks carrying the four enduring praises: SubhanAllah, Alhamdulillah, Allahu Akbar, and La ilaha illa Allah.",
    essayTitleAr: "بؤرة فيروزية وأربعة أركان ذهبية: التوحيد في المركز والباقيات الصالحات في الزوايا",
    essayTitleEn: "Turquoise Core and Four Gold Corners: Monotheism at the Center, the Four Enduring Praises at the Edges",
    spiritualAr: "تلتقي كلمات الباقيات الصالحات والذكر الشريف لتدور في فلك كلمة الإخلاص والتوحيد الطاهر. تمثل هذه العجلة الكونية منار الهداية الرباني، حيث تشع بؤرتها الفيروزية سماحة ونوراً لا غنى عنه لكل روح، ملهمةً السكون الوجداني والتدبر والصفاء الروحي في مجالسكم الفخمة والرقية.",
    spiritualEn: "Sacred phrases of daily praise revolve around the absolute focal truth of monotheism. Represented by a gorgeous geometric wheel, this luxury painting serves as a beacon of cosmic balance and enlightenment, warming any elegant drawing room with protective energies and boundless joy.",
    geometricAr: "تصميم كوني معقد للغاية يضم مركزاً دائرياً ملوناً باللون الفيروزي الياقوتي الشريف يحمل حقيقة الإخلاص تلتف حوله كتابات مذهبة ومحددة بدقة تامة. تحف أطراف اللوحة زوايا مذهبة دقيقة للكلمات الباقيات لتبرز الاتزان الرياضي وفخامة التركيب المعماري اليدوي الشاهق والمحبوك.",
    geometricEn: "This masterpiece groups the calligraphic scripts into an intricate circular shield centered by a vibrant cobalt-cyan core. The four corners house symmetrically aligned gold cartouches write words of praise, showing exceptional mastery over multi-directional grid coordinates."
  },
  {
    id: "surah-falaq-grid",
    titleAr: "سبحان الله و الحمد لله و الله أكبر ",
    titleEn: "Surah Al-Falaq - The Daybreak",
    subtitleAr: "لوحة فنية تجسيد الحمد و التسبيح و التوحيد ",
    subtitleEn: "Classic Square Kufic grid of Surah Al-Falaq on black background",
    price: 160,
    image: "/images/article_32_1629643976.jpeg",
    category: "geometric",
    size: "45x45 سم",
    limitedEdition: true,
    descriptionAr: "لوحة «سبحان الله و الحمد لله و الله أكبر» تجمع التسبيح والحمد والتكبير في شبكة كوفية مربعة متناظرة، مزينة بنقاط تشكيل موزعة بدقة على الحروف، في تكوين يجسد الأذكار الثلاثة كصرح كوفي للذكر والشكر.",
    descriptionEn: "Complete Surah Al-Falaq structured in a symmetric Square Kufic grid in gold on matte black background, decorated with precisely placed saffron-yellow vowel dots on the letters to improve readability of the verses.",
    essayTitleAr: "سورة الفلق في شبكة كوفية سوداء بنقاط زعفرانية: الحماية الإلهية في بنية هندسية محكمة",
    essayTitleEn: "Surah Al-Falaq in a Square Kufic Grid with Yellow Vowel Dots: Divine Protection in a Tight Geometric Structure",
    spiritualAr: "تعد سورة الفلق درعاً حصيناً يعصم النفوس ويبدد ظلام القلق والشرور بنور الفلق الصاعد الآمن المبهج. تقدم هذه اللوحة الكوفية المربعة لمقتنيها حصانة كاملة وسلاماً عائلياً دافئاً يبث الطمأنينة الكاملة والسكينة والرضوان بين القلوب ويورث السعادة والسكينة الرفيعة.",
    spiritualEn: "Celebrated as an impenetrable shield against unseen worries, Surah Al-Falaq welcomes the radiant morning light of hope and celestial protection. Displayed in high-end spaces, this canvas functions as a calligraphic guardian, fostering a serene, clean energy.",
    geometricAr: "صِيغت سورة الفلق كاملة ضمن شبكة كوفية تربيعية ثنائية التباين كوفية شديدة الإتقان على خلفية سوداء ناصعة وراقية. تم توزيع النقاط والتشكيلات الذهبية والصفراء بدقة متناهية لتبرز الحدود الهندسية للحروف وتسهل الفك البصري للآيات الكوفية بدراسة واضحة.",
    geometricEn: "Reconstructing the entire Surah within a strict 1:1 ortholinear grid, the letter lines are hand-detailed in gold leaf over a deep matte obsidian backdrop. Beautiful saffron-yellow vowels are strategically positioned, improving readability and highlighting the geometric corners."
  },
  {
    id: "sapphire-star-kufic",
    titleAr: "لا إله إلا الله محمد رسول الله ",
    titleEn: "The Sapphire Celestial Star",
    subtitleAr: "تصميم مزخرف يجسد كلمة التوحيد في شكل صومعات و قباب ",
    subtitleEn: "Perfect 8-pointed star calligraphy in rich gold leaf on indigo canvas",
    price: 300,
    image: "/images/article_33_1390136691.jpeg",
    category: "geometric",
    size: "66x53 سم",
    limitedEdition: true,
    descriptionAr: "شهادة «لا إله إلا الله محمد رسول الله» منفذة في نجمة ثمانية الأضلاع، في تصميم مزخرف يجسد كلمة التوحيد في شكل صومعات وقباب كوفية تمنح اللوحة وقاراً بصرياً فريداً.",
    descriptionEn: "An 8-pointed star executed in premium matte-gold acrylic pigment on a deep royal indigo linen canvas, where the contrast between the matte finish and the dark velvet background creates a uniquely deep and dignified visual presence.",
    essayTitleAr: "نجمة ذهبية مطفأة على كتان الإنديغو العميق: ثمانية أضلاع كوفية في ظلال الزرقة الملكية",
    essayTitleEn: "Matte Gold 8-Pointed Star on Deep Indigo Linen: Eight Square Kufic Blades Against Royal Velvet Blue",
    spiritualAr: "يحاكي الكوكب الدري في تدرجاته نبل الروح وصعود الإيمان ونقاء النفس المؤمنة الطاهرة تسبح باسم الخالق البديع. يشع هذا النجم سحراً وجلالاً كلاسيكياً يأخذ الأبصار، غامراً الغرفة بروح السلام والأمان والبركات والأنوار الإلهية الدائمة التي تبهج الوجدان.",
    spiritualEn: "Mirroring the luminous celestial bodies in their alignment, this geometric masterpiece highlights themes of spiritual purity and continuous divine praise. The gold star radiates brilliant peace and intellectual class, transforming any clean wall into a tranquil spiritual focal point.",
    geometricAr: "نجمة ثمانية الأضلاع مبنية بماء الذهب المطفي واللمعان البراق على خلفية من الكتان الكحلي النيلي العتيق الفخم. تم موازنة تقاطع الخطوط وحفر التفاصيل يدويًا لضمان تماثل تام لا تشوبه شائبة، مظهرة براعة محسن نصائيبة في صياغة الفنون الهندسية للأبعاد العتيقة المتميزة.",
    geometricEn: "This octagram is designed over a radial coordinate system using premium matte-gold acrylics on a rich deep-indigo linen surface. Every intersecting angle is measured precisely, maintaining absolute dimensional symmetry and highlighting straight Kufic corners."
  },
  {
    id: "six-minaret-mosque",
    titleAr: "نَرْفَعُ دَرَجَاتٍ مَّن نَّشَاءُ ۗ وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ",
    titleEn: "The Cathedral of Six Minarets",
    subtitleAr: "رسم معماري كوفي فخم للأية 76 من سورة يوسف",
    subtitleEn: "Architectural Kufic layout of a six-minaret mosque in gold lacquer",
    price: 350,
    image: "/images/article_34_1316526574.jpeg",
    category: "luxury",
    size: "70x48 سم",
    limitedEdition: true,
    descriptionAr: "آية «نَرْفَعُ دَرَجَاتٍ مَّن نَّشَاءُ ۗ وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ» من سورة يوسف مرسومة في مخطط معماري كوفي فخم: ستة مآذن رأسية شاهقة متناظرة على جانبين مع قبة دائرية مركزية، كلها منفذة يدوياً، في ربط بين علو الدرجات وعظمة العمارة الإسلامية.",
    descriptionEn: "A calligraphic architectural blueprint of a mosque: six tall symmetrical minarets on both sides flanking a central circular dome, all hand-executed in gold Square Kufic on deep black background.",
    essayTitleAr: "مخطط مسجد كوفي ذهبي: ستة مآذن رأسية وقبة مركزية مرسومة بالخط المربع",
    essayTitleEn: "Six-Minaret Mosque in Gold Kufic: An Architectural Blueprint with Six Spires and a Central Dome",
    spiritualAr: "يمثل المسجد النبوي الشريف رمزاً للمحبة والمودة والرحمة والاجتماع البشري المبارك على هدي الإيمان والنور الصافي. يجسد هذا العمل الفخم هيبة الصروح وعظمة العمارة الإسلامية التاريخية الكبرى، ناشراً السكينة والوقار والبركات المباركة والأنوار في الفراغ بشكل إمبراطوري رائع الجلال والمهابة.",
    spiritualEn: "Synthesizing the visual glory of the Prophet's Holy Mosque in Madinah, this monumental artwork honors sacred architecture as a place of infinite mercy and spiritual assembly. It radiates an unmatched presence of cultural authority, deep sacred dignity, and domestic abundance.",
    geometricAr: "هذه واحدة من أهم لوحات المعرض، حيث صُمم هذا الصرح الهندسي المذهل لجمع 6 مآذن شاهقة الارتفاع مع قبة دائرية بالخط المذهب في تجانس معماري فريد. تم احتساب النقاط والكتل والظلال بدقة يدوية متناهية لتنسيق التباين البصري وتأكيد الرسوخ الهندسي الكوفي الشامخ بصفاء وبهاء التراث الفني.",
    geometricEn: "Representing one of the collection's crown jewels, this massive blueprint is engineered to accommodate six vertical calligraphic spires surrounding a beautifully calculated central dome in rich gold paint. The symmetry balances high-density vertical lines with horizontal plinths, establishing exceptional stability."
  },
  {
    id: "infinity-symbol-praise",
    titleAr: "قُلْ إِنَّ رَبِّي يَبْسُطُ الرِّزْقَ لِمَن يَشَاءُ مِنْ عِبَادِهِ وَيَقْدِرُ لَهُ ۚ وَمَا أَنفَقْتُم مِّن شَيْءٍ فَهُوَ يُخْلِفُهُ ۖ وَهُوَ خَيْرُ الرَّازِقِينَ",
    titleEn: "The Infinity Symbol and Praise",
    subtitleAr: "سورة : سبأ:الآية رقم 39 ",
    subtitleEn: "Infinite geometric Kufic loops representing eternal divine praise",
    price: 220,
    image: "/images/article_35_2112499819.jpeg",
    category: "geometric",
    size: "51x47 سم",
    limitedEdition: true,
    descriptionAr: "آية «قُلْ إِنَّ رَبِّي يَبْسُطُ الرِّزْقَ لِمَن يَشَاءُ مِنْ عِبَادِهِ وَيَقْدِرُ لَهُ ۚ وَمَا أَنفَقْتُم مِّن شَيْءٍ فَهُوَ يُخْلِفُهُ ۖ وَهُوَ خَيْرُ الرَّازِقِينَ» من سورة سبأ مصنوعة في شكل اللانهاية (∞) من حروف كوفية تربيعية، حيث يشكّل انسياب الحروف منحنيات الحلقة اللانهائية في تكوين يربط بين الرزق الإلهي والذكر الأبدي.",
    descriptionEn: "The infinity symbol (∞) built entirely from Square Kufic letter strokes reading divine praises, where the flow of the letters themselves forms the twin loops of the infinity path, hand-painted in gold on deep black.",
    essayTitleAr: "رمز ∞ مصنوع من حروف التسبيح الكوفية: حين تشكّل الأذكار شكل اللانهاية",
    essayTitleEn: "The Infinity Symbol Built from Kufic Praise Letters: When Divine Remembrance Forms the ∞ Shape",
    spiritualAr: "يرمز شكل اللانهاية إلى دوام الذكر والتسبيح الذي لا ينقطع، وأزل الحقيقة الإلهية التي تتجاوز كل الزمان والمكان. تحمل هذه اللوحة روح السكينة الدائمة والاتصال المستمر بالخالق سبحانه وتعالى.",
    spiritualEn: "The infinity symbol represents the eternal, never-ending remembrance and praise of God, transcending all time and space. This masterpiece embodies perpetual spiritual connection and continuous divine communion.",
    geometricAr: "تصميم معقد يمزج بين الخطوط الكوفية المربعة والشكل الهندسي للانهاية، خلق توازن بصري فريد يجذب الأنظار في حركة دائبة. كل منحنى وكل خط حسب بدقة لضمان انسيابية الشكل واستمراريته.",
    geometricEn: "A sophisticated blend of Square Kufic lines with the infinity symbol's geometric form, creating a unique visual balance that draws the eye in perpetual motion. Every curve and stroke is meticulously calculated for seamless continuity."
  },
  {
    id: "geometric-balance-bismillah",
    titleAr: "أسماء الله الحسنى ال99 ",
    titleEn: "The Geometric Balance - Blessed Bismillah",
    subtitleAr: "لوحة تجسد أسماء الله الحسنى ال99 بالخط الكوفي التربيعي ",
    subtitleEn: "Perfect geometric balance of the Bismillah in symmetrical Kufic arrangement",
    price: 700,
    image: "/images/article_36_1121400077.jpeg",
    category: "luxury",
    size: "85x66 سم",
    limitedEdition: true,
    descriptionAr: "«أسماء الله الحسنى ال99» مرسومة بالخط الكوفي التربيعي في تكوين متناظر تماماً، حيث يتوزع كل اسم في شبكة هندسية محكمة يعادل فيها ثقل النصف الأيمن النصف الأيسر بدقة رياضية مطلقة، في لوحة تجسد جمال الأسماء الحسنى وعظمتها الكوفية.",
    descriptionEn: "'Bismillah Ar-Rahman Ar-Rahim' in Square Kufic arranged in a perfectly balanced layout where the right half of the composition carries exactly equal visual weight to the left, achieving absolute geometric and mathematical equilibrium in gold on black.",
    essayTitleAr: "البسملة في ميزان كوفي مثالي: النصف الأيمن يعادل الأيسر في وزن بصري ورياضي دقيق",
    essayTitleEn: "Bismillah on a Perfect Kufic Scale: Right Half Equaling Left in Absolute Visual and Mathematical Balance",
    spiritualAr: "البسملة هي مفتاح الخير وبركة كل عمل، وتصويرها على ميزان هندسي يعكس العدل الإلهي والتوازن الأزلي في الكون. هذه اللوحة تبعث روح الاستقرار والطمأنينة والثقة بعدل الخالق الجليل.",
    spiritualEn: "The Bismillah is the gateway to all blessings, and depicting it on a geometric scale reflects divine justice and eternal cosmic balance. This artwork radiates stability, peace, and unwavering trust in divine equilibrium.",
    geometricAr: "تصميم معماري متقن يضع البسملة على ميزان كوفي مربع متناسق تماماً. كل حرف يزن بالضبط مثل نظيره، مخلقاً توازناً بصرياً وهندسياً دقيقاً يعكس دقة الخالق في خلقه.",
    geometricEn: "A masterfully crafted architectural design placing the Bismillah on a perfectly balanced Square Kufic scale. Each letter weighs precisely as its counterpart, creating an exquisite visual and geometric equilibrium reflecting divine precision."
  },
  {
    id: "niche-righteous",
    titleAr: "بسم الله الرحمن الرحيم",
    titleEn: "The Righteous' Niche - Testament of Faith",
    subtitleAr: "لوحة مزخرفة تجسد البسمله ",
    subtitleEn: "A sacred Kufic niche housing the Islamic declaration of faith",
    price: 350,
    image: "/images/article_37_1715587981.jpeg",
    category: "luxury",
    size: "67x39 سم",
    limitedEdition: true,
    descriptionAr: "«بسم الله الرحمن الرحيم» مكتوبة بالخط الكوفي المربع داخل محراب معماري فخم يحتضن البسملة بكل روعتها، مصنوع بأعلى مستويات الدقة الكوفية والهندسية، في لوحة مزخرفة تجسد البسملة كبوابة بركة ونور.",
    descriptionEn: "A magnificent architectural niche embracing the Islamic testament of faith, crafted with the highest standards of Kufic and geometric precision.",
    essayTitleAr: "مِحْرَابُ التَّوْحِيدِ: الشَّهَادَةُ الإسْلَامِيَّةُ فِي قَلْبِ الهَنْدَسَة الكُوفِيَّة",
    essayTitleEn: "The Mihrab of Monotheism: Islamic Testament in the Heart of Kufic Architecture",
    spiritualAr: "يجسد المحراب المكان المقدس للصلاة والدعاء، والشهادة الإسلامية هي قلب التوحيد وأساس الإيمان. هذا العمل الفخم ينشر روح التقوى والتسليم الكامل لله وحده.",
    spiritualEn: "The niche represents the sacred space of prayer and supplication, while the Islamic testament forms the heart of monotheism and foundation of faith. This magnificent work spreads the spirit of piety and complete submission to God alone.",
    geometricAr: "تصميم معماري متكامل يشكل محراباً كوفياً مقدساً بالشهادة الإسلامية في المركز. كل خط وكل زاوية محسوبة بدقة متناهية لخلق هندسة مقدسة تعكس الدقة الإلهية.",
    geometricEn: "An integrated architectural design forming a sacred Kufic niche with the Islamic testament at its center. Every line and angle meticulously calculated to create sacred geometry reflecting divine precision and spiritual magnitude."
  }
];

export const BIOGRAPHY = {
  ar: {
    story: "محسن نصائيبة، فنان تشكيلي تونسي رائد كرس عمره لإتقان وتجديد الخط الكوفي المربع والمعاصر. يسعى لإعادة صياغة جماليات الخط العربي الأصيل في قوالب هندسية فخمة تليق بأرقى المعارض وصالونات الفنون الدولية. حازت لوحاته على جوائز وتقدير فني من مقتنيين عبر العالم.",
    technique: "تعتمد الهندسة الكوفية على دقة رياضية متناهية، حيث يتم بناء الحروف الكوفية يدويًا سطرًا بسطر. عملية البناء والتلوين ببريق اللون الذهبي الفاخر الراقي تستغرق ساعات طويلة من التركيز المتواصل لخلق لوحة تحاكي العمارة وتفيض بالنور والجمال الروحي."
  },
  en: {
    story: "Mohsen Nsaibia is a leading Tunisian plastic artist who dedicated his career to refining and modernizing Square and Contemporary Kufic calligraphy. He aims to recreate authentic Arabic script aesthetics in majestic architectural layouts fitting the world's most premium galleries. His works are highly sought after by international collectors.",
    technique: "Kufic geometry demands absolute mathematical precision, constructing Arabic letters hand-painted row by row. This slow work combined with meticulous gold-color lacquer layering results in a timeless painting mimicking architectural structures, bringing spiritual glow into modern spaces."
  }
};

// Bilingual dictionary for ui elements
export const TRANSLATIONS = {
  ar: {
    brandName: "محسن نصائيبة",
    brandTitle: "الخط الكوفي التربيعى المعاصر",
    navHome: "الرئيسية",
    navGallery: "المعرض",
    navSira: "السيرة",
    navContact: "اتصل بنا",
    heroTitle: "روائع الخط الكوفي المربع",
    heroSubtitle: "الفنان التونسي محسن نصائيبة — حوار الحبر واللون الذهبي الراقي",
    heroDsc: "انغمس في عالم من الفخامة البصرية حيث تلتقي الأصالة بالحداِثة في كل لمسة فرشاة ذهبية مجسّدة في هندسة الكوفي المربع المذهلة.",
    btnExplore: "استكشف المعرض",
    btnBio: "سيرة الفنان",
    philosophyTitle: "الفلسفة الفنية",
    philosophySub: "حوار الحبر واللون الذهبي الراقي",
    philosophyDsc: "تتمحور أعمال محسن نصائيبة حول تجسيد الهندسة الكوفية بأسلوب معاصر. كل لوحة هي رحلة في أعماق التراث العربي، حيث يتم تحويل الكلمات إلى أشكال معمارية تتراقص فيها الظلال والأنوار الذهبية المتألقة.",
    metricExp: "سنوات الخبرة الفنية",
    metricCollected: "أعمال أصلية مقتناة",
    craftTitle: "THE CRAFT",
    craftSubtitle: "إتقان الأدوات والتقنيات",
    craftFeature1Title: "جمال تركيب الخشب المتناظر",
    craftFeature1Dsc: "يتم استخدام خامات خشب ومواد مصنعة يدوياً لتوزيع طبقات اللون الذهبي الفاخر وتركيبها بدقة، لخلق أعماق بصرية ثلاثية الأبعاد تحاكي فخامة الحفر الهندسي.",
    craftFeature2Title: "بلور واقي فاخر معرضي مضاد للانعكاس",
    craftFeature2Dsc: "نحفظ كل لوحة تحت طبقة بلور فاخرة مقاومة للانعكاس والغبار، مما يحمي بريق الألوان الذهبية المتناسقة وتفاصيل الخشب من الرطوبة أو التغيرات الجوية لقرون.",
    craftFeature3Title: "الدقة الهندسية والرياضية المطلقة",
    craftFeature3Dsc: "التركيز على الكوفي المربع يتطلب دقة رياضية فائقة، حيث يتم رسم كل خط هندسي ووحدة بنائية يدوياً لضمان توازن مثالي بين الكتل والظلال.",
    curatedTitle: "THE CURATED COLLECTION",
    curatedSubtitle: "الأعمال الفنية الأصلية للفنان محسن نصائيبة بأسعارها المعتمدة شاملة الإطار والبلور الأثري",
    galleryFilterAll: "الكل",
    galleryFilterLuxury: "الروائع الكلاسيكية",
    galleryFilterGeometric: "اللوحات المعمارية والهندسية",
    galleryFilterLettering: "حروفيات معاصرة",
    btnViewFull: "عرض المعرض الكامل",
    currency: "د.ت",
    limitedTag: "عمل أصلي فريد",
    standardTag: "عمل أصلي أصيل",
    btnPurchase: "امتلاك كعمل فني",
    immTitle: "صبر وإتقان خطي",
    immDsc: "يستغرق العمل الفني الواحد ما بين 40 إلى 120 ساعة من التركيز المتواصل، حيث يتم تكوين كل خط هندسي ورسمه وتلوينه يدوياً وبدقة متناهية لضمان توازن بصري وروحي مطلق.",
    immBtn: "شاهد المعرض الداخلي",
    newsletterTitle: "انضم إلى قائمة المقتنين الفنيين",
    newsletterSub: "اشترك في قائمتنا البريدية الخاصة لتلقي دعوات للمعارض المغلقة والحصول على الأولوية في اقتناء اللوحات الحصرية الجديدة.",
    newsletterPlaceholder: "عنوان بريدك الإلكتروني الشخصي",
    newsletterBtn: "اشتراك الآن في القائمة",
    newsletterSuccess: "شكرًا لاهتمامكم الرفيع. لقد تم إدراج بريدكم الإلكتروني ضمن قائمة Collectors الخاصة بالمنتسبين الفنيين لمحسن نصائيبة.",
    cartTitle: "حقيبة المقتنيات الخاصة بك",
    cartEmpty: "حقيبتك فارغة حالياً. تصفح المعرض واختر اللوحات التي تلامس روحك.",
    cartTotal: "المجموع الكلي للاقتناء:",
    cartCheckoutBtn: "تأكيد الطلب وحجز اللوحات",
    cartFrameSelect: "الإطار المعرضي المختار:",
    footerStory: "فنان تونسي رائد متخصص في الخط الكوفي المربع وسحر الحروفيات المعاصرة. غايته إثراء الفراغات الفاخرة بالنور الإلهي والمشغولات الفنية المعمارية النادرة.",
    footerLinks: "روابط سريعة",
    footerContact: "اتصل بنا مباشرة",
    aboutArtist: "حول الفنان التونسي محسن نصائيبة",
    authBtnTitle: "حسابي",
    authTitle: "تسجيل الدخول والعضوية",
    authSub: "أنشئ حسابك أو سجّل دخولك لمتابعة اقتناءاتك وحجوزاتك في المعرض.",
    authSignIn: "تسجيل الدخول",
    authSignUp: "إنشاء حساب",
    authName: "الاسم الكامل",
    authEmail: "البريد الإلكتروني",
    authPassword: "كلمة المرور",
    authLoginBtn: "دخول",
    authRegisterBtn: "تسجيل",
    authLogoutBtn: "تسجيل الخروج",
    authWelcome: "مرحباً",
    authLoggedInAs: "مسجّل الدخول باسم",
    authErrorInvalid: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    authErrorEmailExists: "هذا البريد الإلكتروني مستخدم مسبقاً.",
    authSuccessLogin: "تم تسجيل الدخول بنجاح.",
    authSuccessSignup: "تم إنشاء حسابك وتسجيل الدخول بنجاح.",
    authErrorServer: "حدث خطأ في الاتصال بالخادم. يرجى المحاولة مرة أخرى.",
    // Order Tracking
    ordersTitle: "طلباتي",
    ordersBtnTitle: "تتبع طلباتي",
    ordersEmpty: "لا توجد طلبات حالياً. اقتنِ لوحاتك الفنية المفضلة وستظهر طلباتك هنا.",
    ordersOrderId: "رقم الطلب",
    ordersDate: "تاريخ الطلب",
    ordersStatus: "حالة الطلب",
    ordersItems: "اللوحات المقتناة",
    ordersTotal: "المجموع الكلي",
    ordersShipping: "معلومات التوصيل",
    ordersStatusPending: "قيد المراجعة",
    ordersStatusConfirmed: "تم التأكيد",
    ordersStatusShipped: "تم الشحن",
    ordersStatusDelivered: "تم التسليم",
    ordersStepReceived: "تم الاستلام",
    ordersStepConfirmed: "تأكيد الفنان",
    ordersStepShipped: "قيد التوصيل",
    ordersStepDelivered: "تم التسليم",
    ordersClearAll: "مسح سجل الطلبات",
    // Testimonials
    testimonialsTitle: "ما يقوله المقتنون",
    testimonialsSub: "آراء وشهادات من مقتنين حقيقيين حول العالم",
    testimonialsTag: "شهادات المقتنين",
    // Loading
    loadingText: "جارٍ تحميل المعرض الفني...",
    // Back to top
    backToTop: "العودة للأعلى",
    // WhatsApp
    whatsappTooltip: "تواصل مع الفنان عبر واتساب"
  },
  en: {
    brandName: "Mohsen Nsaibia",
    brandTitle: "Contemporary Square Kufic",
    navHome: "Home",
    navGallery: "Gallery",
    navSira: "Biography",
    navContact: "Contact",
    heroTitle: "Masterpieces of Square Kufic",
    heroSubtitle: "Tunisian Calligrapher Mohsen Nsaibia — Symmetry of Ink & Gold Paint Layers",
    heroDsc: "Immerse yourself in a world of visual luxury where authenticity meets contemporary design in every rich golden-lacquered stroke, captured in majestic Square Kufic alignments.",
    btnExplore: "Explore Gallery",
    btnBio: "Spiritual Biography",
    philosophyTitle: "Artistic Philosophy",
    philosophySub: "A Dialogue of Geometry & Gold Lacquer Layers",
    philosophyDsc: "Mohsen Nsaibia's works center on reconstructing ancient Arabic letterings through contemporary architecture grids. Each painting represents a sacred visual meditation where shadows dance with vibrant golden flares.",
    metricExp: "Years of Craft Mastership",
    metricCollected: "Acquired Artworks Worldwide",
    craftTitle: "THE CRAFT",
    craftSubtitle: "Mastering Tools & Techniques",
    craftFeature1Title: "Symmetric Handmade Wooden Foundations",
    craftFeature1Dsc: "Each painting comes beautifully handmade on elegant wood foundations with layers of warm gold-tone acrylics, preserving absolute visual proportions.",
    craftFeature2Title: "Anti-Reflective Premium Museum Glass",
    craftFeature2Dsc: "Safeguard custom wood segments and deep golden-lacquer details beneath a bespoke glare-free glass shield, resilient to all atmospheric changes.",
    craftFeature3Title: "Total Geometric & Mathematical Purity",
    craftFeature3Dsc: "Square Kufic layout requires ultimate vector calculation, as each single segment is traced and hand-painted to retain seamless aesthetic stability.",
    curatedTitle: "THE CURATED COLLECTION",
    curatedSubtitle: "Bespoke Masterpieces and Original Canvas Art by Mohsen Nsaibia (Complete with Framing & Museum Protection)",
    galleryFilterAll: "All Artworks",
    galleryFilterLuxury: "Luxury Classics",
    galleryFilterGeometric: "Geometric Grids",
    galleryFilterLettering: "Contemporary",
    btnViewFull: "View Full Sacred Collection",
    currency: "DT",
    limitedTag: "Unique Original",
    standardTag: "Bespoke Calligraphy",
    btnPurchase: "Acquire Painting",
    immTitle: "Patience and Mastery",
    immDsc: "A single painting requires 40 to 120 hours of continuous focus. Hand-tracing and expert gold-color layering ensures absolute visual equilibrium and deep spiritual serenity.",
    immBtn: "View Studio Video",
    newsletterTitle: "Join the Collectors Guild",
    newsletterSub: "Subscribe to receive exclusive invitations to private gallery previews and priority reservation lists for unreleased original paintings.",
    newsletterPlaceholder: "Enter your personal email address",
    newsletterBtn: "Register in Guild",
    newsletterSuccess: "Thank you for your refined interest. Your email has been added to Mohsen Nsaibia's VIP Collectors Registry.",
    cartTitle: "Your Personal Art Cart",
    cartEmpty: "Your cart is unoccupied. Discover our works to select calligraphies that resonate with your space.",
    cartTotal: "Total Collection Value:",
    cartCheckoutBtn: "Confirm & Secure Artworks",
    cartFrameSelect: "Selected Frame Style:",
    footerStory: "A seasoned Tunisian plastic artist dedicating code and craft to Square Kufic calligraphy. Infusing premium modern architecture with ancient spiritual light.",
    footerLinks: "Quick Navigation",
    footerContact: "Direct Artist Desk",
    aboutArtist: "About Tunisian Artist Mohsen Nsaibia",
    authBtnTitle: "My Account",
    authTitle: "Sign In & Account",
    authSub: "Create an account or sign in to track your acquisitions and gallery reservations.",
    authSignIn: "Sign In",
    authSignUp: "Sign Up",
    authName: "Full Name",
    authEmail: "Email Address",
    authPassword: "Password",
    authLoginBtn: "Log In",
    authRegisterBtn: "Create Account",
    authLogoutBtn: "Log Out",
    authWelcome: "Welcome",
    authLoggedInAs: "Signed in as",
    authErrorInvalid: "Invalid email or password.",
    authErrorEmailExists: "This email is already registered.",
    authErrorServer: "There was a problem connecting to the server. Please try again.",
    authSuccessLogin: "You have signed in successfully.",
    authSuccessSignup: "Your account was created and you are now signed in.",
    // Order Tracking
    ordersTitle: "My Orders",
    ordersBtnTitle: "Track My Orders",
    ordersEmpty: "No orders yet. Acquire your favorite artworks and your orders will appear here.",
    ordersOrderId: "Order ID",
    ordersDate: "Order Date",
    ordersStatus: "Status",
    ordersItems: "Acquired Artworks",
    ordersTotal: "Total Value",
    ordersShipping: "Shipping Details",
    ordersStatusPending: "Under Review",
    ordersStatusConfirmed: "Confirmed",
    ordersStatusShipped: "Shipped",
    ordersStatusDelivered: "Delivered",
    ordersStepReceived: "Received",
    ordersStepConfirmed: "Artist Confirmed",
    ordersStepShipped: "In Transit",
    ordersStepDelivered: "Delivered",
    ordersClearAll: "Clear Order History",
    // Testimonials
    testimonialsTitle: "What Collectors Say",
    testimonialsSub: "Authentic testimonials from distinguished collectors worldwide",
    testimonialsTag: "COLLECTOR TESTIMONIALS",
    // Loading
    loadingText: "Loading the Art Gallery...",
    // Back to top
    backToTop: "Back to Top",
    // WhatsApp
    whatsappTooltip: "Contact the Artist via WhatsApp"
  }
};

export const KUFIC_CHARACTERS_MAP: { [key: string]: boolean[][] } = {
  // Let's model a 4x4 matrix representation of lines for Arabic letters in grid style
  default: [
    [true, false, true, true],
    [true, false, true, false],
    [true, true, true, false],
    [false, false, true, true]
  ],
  "أ": [
    [true, false, false, false],
    [true, false, false, false],
    [true, false, false, false],
    [true, false, false, false]
  ],
  "ب": [
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ت": [
    [true, true, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ج": [
    [true, true, true, true],
    [false, false, false, true],
    [true, true, true, true],
    [true, false, false, false]
  ],
  "ح": [
    [true, true, true, true],
    [false, false, false, true],
    [true, true, true, true],
    [true, false, false, false]
  ],
  "خ": [
    [true, true, true, true],
    [false, false, false, true],
    [true, true, true, true],
    [true, false, false, false]
  ],
  "د": [
    [true, true, true, true],
    [true, false, false, false],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ر": [
    [true, false, false, false],
    [true, false, false, false],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "س": [
    [true, false, true, false],
    [true, false, true, false],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ش": [
    [true, true, true, false],
    [true, false, true, false],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ص": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ط": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, false, false, false]
  ],
  "ع": [
    [true, true, true, true],
    [true, false, false, true],
    [true, false, false, false],
    [true, true, true, true]
  ],
  "ف": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, false, false, false]
  ],
  "ق": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, false, false, true]
  ],
  "ك": [
    [true, false, false, false],
    [true, false, true, true],
    [true, false, false, true],
    [true, true, true, true]
  ],
  "ل": [
    [true, false, false, false],
    [true, false, false, false],
    [true, false, false, false],
    [true, true, true, true]
  ],
  "م": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ن": [
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ه": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, false, false, true]
  ],
  "و": [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, false]
  ],
  "ي": [
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, true, false, false]
  ]
};
